l_polish:
 SETTING_INPUT_CONTEXT_COMMON:0 "Standardowe"
 SETTING_INPUT_CONTEXT_COMMON_TOOLTIP:1 "Przypisania klawiszy – standardowe dane wejściowe"

 SETTING_INPUT_ACTION_PAUSE:0 "Wstrzymaj/wznów"
 SETTING_INPUT_ACTION_INCREASE_SPEED:0 "Zwiększ szybkość"
 SETTING_INPUT_ACTION_DECREASE_SPEED:0 "Zmniejsz szybkość"
 SETTING_INPUT_ACTION_SPEED_ONE:0 "Szybkość 1"
 SETTING_INPUT_ACTION_SPEED_TWO:0 "Szybkość 2"
 SETTING_INPUT_ACTION_SPEED_THREE:0 "Szybkość 3"
 SETTING_INPUT_ACTION_SPEED_FOUR:0 "Szybkość 4"
 SETTING_INPUT_ACTION_SPEED_FIVE:0 "Szybkość 5"
 SETTING_INPUT_ACTION_PLAY_PAUSE_MUSIC:0 "Odtwarzaj/wstrzymaj muzykę"
 SETTING_INPUT_ACTION_NEXT_MUSIC_TRACK:0 "Następny utwór"
 SETTING_INPUT_ACTION_CAMERA_UP:0 "Przesuń kamerę w górę"
 SETTING_INPUT_ACTION_CAMERA_LEFT:0 "Przesuń kamerę w lewo"
 SETTING_INPUT_ACTION_CAMERA_DOWN:0 "Przesuń kamerę w dół"
 SETTING_INPUT_ACTION_CAMERA_RIGHT:0 "Przesuń kamerę w prawo"
 SETTING_INPUT_ACTION_LOCATION_FINDER:0 "Wyszukiwarka lokalizacji"
 SETTING_INPUT_ACTION_OPEN_POLITICS:0 "Polityka"
 SETTING_INPUT_ACTION_OPEN_BUDGET:0 "Budżet"
 SETTING_INPUT_ACTION_OPEN_BUILDINGS:0 "Budynki"
 SETTING_INPUT_ACTION_OPEN_MARKET:0 "Rynek"
 SETTING_INPUT_ACTION_OPEN_MILITARY:0 "Wojsko"
 SETTING_INPUT_ACTION_OPEN_DIPLOMATIC:0 "Dyplomacja"
 SETTING_INPUT_ACTION_OPEN_TECHNOLOGY:0 "Technologia"
 SETTING_INPUT_ACTION_OPEN_CULTURE:0 "Kultura"
 SETTING_INPUT_ACTION_OPEN_POPULATION:0 "Populacja"
 SETTING_INPUT_ACTION_OPEN_JOURNAL:0 "Dziennik"
 SETTING_INPUT_ACTION_OPEN_DECISIONS:0 "Decyzje"
 SETTING_INPUT_ACTION_MAP_LIST:0 "Księga rachunkowa"
 SETTING_INPUT_ACTION_BACK:0 "Wstecz"
 SETTING_INPUT_ACTION_OPEN_OUTLINER:0 "Przybornik"
 SETTING_INPUT_ACTION_TAB_1:0 "Karta 1"
 SETTING_INPUT_ACTION_TAB_2:0 "Karta 2"
 SETTING_INPUT_ACTION_TAB_3:0 "Karta 3"
 SETTING_INPUT_ACTION_TAB_4:0 "Karta 4"
 SETTING_INPUT_ACTION_TAB_5:0 "Karta 5"
 SETTING_INPUT_ACTION_PRODUCTION_LENS:0 "Obiektyw Produkcja"
 SETTING_INPUT_ACTION_POLITICAL_LENS:0 "Obiektyw Polityka"
 SETTING_INPUT_ACTION_DIPLOMATIC_LENS:0 "Obiektyw Dyplomacja"
 SETTING_INPUT_ACTION_MILITARY_LENS:0 "Obiektyw Wojsko"
 SETTING_INPUT_ACTION_TRADE_LENS:0 "Obiektyw Handel"
 SETTING_INPUT_ACTION_CONFIRM:0 "Zatwierdź"
 SETTING_INPUT_ACTION_CURRENT_SITUATION:0 "Bieżąca sytuacja"
 SETTING_INPUT_ACTION_CONSTRUCTION_QUEUE:0 "Kolejka budowy"
 SETTING_INPUT_ACTION_TOGGLE_CONSTRUCTION_QUEUE_PAUSE:0 "Wstrzymaj/wznów kolejkę budowy"
 SETTING_INPUT_ACTION_GO_TO_DETAILS:0 "Przejdź do szczegółów"
 SETTING_INPUT_ACTION_SCROLL_UP:0 "Przewiń w górę"
 SETTING_INPUT_ACTION_SCROLL_DOWN:0 "Przewiń w dół"
 SETTING_INPUT_ACTION_TOGGLE_GUI_DEBUG:0 "(Debug) gui.debug"
