l_polish:
  
 pm_primary:0 "Podstawowa"
 pmg_secondary_building_rye_farm:0 "Drugorzędna"
 pmg_secondary_building_wheat_farm:0 "Drugorzędna"
 pmg_secondary_building_rice_farm:0 "Drugorzędna"
 pmg_secondary_building_maize_farm:0 "Drugorzędna"
 pmg_secondary_building_millet_farm:0 "Drugorzędna"
 pm_no_secondary:0 "Uprawa jednolita"
 pm_potatoes:0 "Ziemniaki"
 pm_vineyards:0 "Winnice"
 pm_vineyards_building_maize_farm:0 "Winnice"
 pm_apple_orchards:0 "Sady jabłoniowe"
 pm_citrus_orchards:0 "Sady cytrusowe"
 pm_fig_orchards:0 "Sady figowe"
 pm_mulberry_groves:0 "Zagajniki morwowe"

 pmg_automation:0 "Automatyzacja"
 pmg_automation_building_food_industry:0 "Automatyzacja"
 pmg_automation_building_textile_mills:0 "Automatyzacja"
 pmg_automation_building_furniture_manufacturies:0 "Automatyzacja"
 pmg_automation_building_tooling_workshops:0 "Automatyzacja"
 pmg_automation_building_paper_mills:0 "Automatyzacja"
 pmg_automation_building_steel_mills:0 "Automatyzacja"
 pmg_automation_building_motor_industry:0 "Automatyzacja"
 pm_civilian_priority:0 "Priorytet cywilny"
 pm_military_priority:0 "Priorytet wojskowy"

  
 pm_craftsman_sewing:0 "Krawiectwo rzemieślnicze"
 pm_sewing_machines:0 "Maszyny do szycia"
 pm_electric_sewing_machines:0 "Elektryczne maszyny do szycia"
 pm_traditional_looms:0 "Krosna tradycyjne"
 pm_mechanized_looms:0 "Krosna mechaniczne"
 pm_automatic_power_looms:0 "Automatyczne krosna mechaniczne"

  
 pm_leaded_glass:0 "Szkło ołowiowe"
 pm_manual_glassblowing:0 "Tradycyjne dmuchanie szkła"

  
 pm_leblanc_process:0 "Metoda Leblanca"
 pm_no_explosives_production:0 "Priorytetowa produkcja nawozu"
 pm_ammonia-soda_process:0 "Proces amoniakowo-sodowy"
 pm_vacuum_evaporation:0 "Parowanie próżniowe"
 pm_brine_electrolysis:0 "Elektroliza solanki"
 pmg_fertilizer_production:0 "Produkcja nawozu"
 pm_no_artificial_fertilizers:0 "Brak nawozów sztucznych"
 pm_artificial_fertilizers:0 "Nawozy sztuczne"
 pm_improved_fertilizer:0 "Nawozy zmodyfikowane"
 pm_nitrogen_fixation:0 "Proces wiązania azotu cząsteczkowego"
 pm_dyes_production:0 "Produkcja barwników"
 pm_no_synthetic_dyes:0 "Brak barwników syntetycznych"
 pmg_synthetic_dyes:0 "Barwniki syntetyczne"
 pm_silk_production:0 "Produkcja jedwabiu"
 pm_no_artificial_fibers:0 "Priorytetowa produkcja barwnika"
 pm_rayon:0 "Wiskoza"

  
 pm_steamworks:0 "Metody oparte na wykorzystaniu pary"
 pm_no_artillery_production:0 "Priorytetowa produkcja broni krótkiej"
 pm_artillery_production:0 "Produkcja broni artyleryjskiej"

  
 pmg_automobile_production:0 "Produkcja automobilów"
 pm_automobile_production:0 "Produkcja automobilów"
