set charset="empty"
set parser_version="0.1.11"
del /s /f /q dif
java -jar "tools\\LocaleParser\\bin\\LocaleParser-%parser_version%-SNAPSHOT.jar" "folder_diff" "orginal\\game\\localization\\english" "nowe\\game\\localization\\english" "dif\\game\\localization\\english" eu4
java -jar "tools\\LocaleParser\\bin\\LocaleParser-%parser_version%-SNAPSHOT.jar" "folder_diff" "orginal\\game\\localization\\english\\bookmark" "nowe\\game\\localization\\english\\bookmark" "dif\\game\\localization\\english\\bookmark" eu4
java -jar "tools\\LocaleParser\\bin\\LocaleParser-%parser_version%-SNAPSHOT.jar" "folder_diff" "orginal\\game\\localization\\english\\credits" "nowe\\game\\localization\\english\\credits" "dif\\game\\localization\\english\\credits" eu4
java -jar "tools\\LocaleParser\\bin\\LocaleParser-%parser_version%-SNAPSHOT.jar" "folder_diff" "orginal\\game\\localization\\english\\culture" "nowe\\game\\localization\\english\\culture" "dif\\game\\localization\\english\\culture" eu4
java -jar "tools\\LocaleParser\\bin\\LocaleParser-%parser_version%-SNAPSHOT.jar" "folder_diff" "orginal\\game\\localization\\english\\custom_localization" "nowe\\game\\localization\\english\\custom_localization" "dif\\game\\localization\\english\\custom_localization" eu4
java -jar "tools\\LocaleParser\\bin\\LocaleParser-%parser_version%-SNAPSHOT.jar" "folder_diff" "orginal\\game\\localization\\english\\dynasties" "nowe\\game\\localization\\english\\dynasties" "dif\\game\\localization\\english\\dynasties" eu4
java -jar "tools\\LocaleParser\\bin\\LocaleParser-%parser_version%-SNAPSHOT.jar" "folder_diff" "orginal\\game\\localization\\english\\dynasty_legacies" "nowe\\game\\localization\\english\\dynasty_legacies" "dif\\game\\localization\\english\\dynasty_legacies" eu4
java -jar "tools\\LocaleParser\\bin\\LocaleParser-%parser_version%-SNAPSHOT.jar" "folder_diff" "orginal\\game\\localization\\english\\enum" "nowe\\game\\localization\\english\\enum" "dif\\game\\localization\\english\\enum" eu4
java -jar "tools\\LocaleParser\\bin\\LocaleParser-%parser_version%-SNAPSHOT.jar" "folder_diff" "orginal\\game\\localization\\english\\event_localization" "nowe\\game\\localization\\english\\event_localization" "dif\\game\\localization\\english\\event_localization" eu4
java -jar "tools\\LocaleParser\\bin\\LocaleParser-%parser_version%-SNAPSHOT.jar" "folder_diff" "orginal\\game\\localization\\english\\gui" "nowe\\game\\localization\\english\\gui" "dif\\game\\localization\\english\\gui" eu4
java -jar "tools\\LocaleParser\\bin\\LocaleParser-%parser_version%-SNAPSHOT.jar" "folder_diff" "orginal\\game\\localization\\english\\interactions" "nowe\\game\\localization\\english\\interactions" "dif\\game\\localization\\english\\interactions" eu4
java -jar "tools\\LocaleParser\\bin\\LocaleParser-%parser_version%-SNAPSHOT.jar" "folder_diff" "orginal\\game\\localization\\english\\lifestyles" "nowe\\game\\localization\\english\\lifestyles" "dif\\game\\localization\\english\\lifestyles" eu4
java -jar "tools\\LocaleParser\\bin\\LocaleParser-%parser_version%-SNAPSHOT.jar" "folder_diff" "orginal\\game\\localization\\english\\load_tips" "nowe\\game\\localization\\english\\load_tips" "dif\\game\\localization\\english\\load_tips" eu4
java -jar "tools\\LocaleParser\\bin\\LocaleParser-%parser_version%-SNAPSHOT.jar" "folder_diff" "orginal\\game\\localization\\english\\modifiers" "nowe\\game\\localization\\english\\modifiers" "dif\\game\\localization\\english\\modifiers" eu4
java -jar "tools\\LocaleParser\\bin\\LocaleParser-%parser_version%-SNAPSHOT.jar" "folder_diff" "orginal\\game\\localization\\english\\names" "nowe\\game\\localization\\english\\names" "dif\\game\\localization\\english\\names" eu4
java -jar "tools\\LocaleParser\\bin\\LocaleParser-%parser_version%-SNAPSHOT.jar" "folder_diff" "orginal\\game\\localization\\english\\opinions" "nowe\\game\\localization\\english\\opinions" "dif\\game\\localization\\english\\opinions" eu4
java -jar "tools\\LocaleParser\\bin\\LocaleParser-%parser_version%-SNAPSHOT.jar" "folder_diff" "orginal\\game\\localization\\english\\portraits" "nowe\\game\\localization\\english\\portraits" "dif\\game\\localization\\english\\portraits" eu4
java -jar "tools\\LocaleParser\\bin\\LocaleParser-%parser_version%-SNAPSHOT.jar" "folder_diff" "orginal\\game\\localization\\english\\religion" "nowe\\game\\localization\\english\\religion" "dif\\game\\localization\\english\\religion" eu4
java -jar "tools\\LocaleParser\\bin\\LocaleParser-%parser_version%-SNAPSHOT.jar" "folder_diff" "orginal\\game\\localization\\english\\triggers" "nowe\\game\\localization\\english\\triggers" "dif\\game\\localization\\english\\triggers" eu4

java -jar "tools\\LocaleParser\\bin\\LocaleParser-%parser_version%-SNAPSHOT.jar" "folder_diff" "orginal\\game\\localization\\english\\event_localization\\activities" "nowe\\game\\localization\\english\\event_localization\\activities" "dif\\game\\localization\\english\\event_localization\\activities" eu4
java -jar "tools\\LocaleParser\\bin\\LocaleParser-%parser_version%-SNAPSHOT.jar" "folder_diff" "orginal\\game\\localization\\english\\event_localization\\childhood" "nowe\\game\\localization\\english\\event_localization\\childhood" "dif\\game\\localization\\english\\event_localization\\childhood" eu4
java -jar "tools\\LocaleParser\\bin\\LocaleParser-%parser_version%-SNAPSHOT.jar" "folder_diff" "orginal\\game\\localization\\english\\event_localization\\councillor_task_events" "nowe\\game\\localization\\english\\event_localization\\councillor_task_events" "dif\\game\\localization\\english\\event_localization\\councillor_task_events" eu4
java -jar "tools\\LocaleParser\\bin\\LocaleParser-%parser_version%-SNAPSHOT.jar" "folder_diff" "orginal\\game\\localization\\english\\event_localization\\culture_events" "nowe\\game\\localization\\english\\event_localization\\culture_events" "dif\\game\\localization\\english\\event_localization\\culture_events" eu4
java -jar "tools\\LocaleParser\\bin\\LocaleParser-%parser_version%-SNAPSHOT.jar" "folder_diff" "orginal\\game\\localization\\english\\event_localization\\death_events" "nowe\\game\\localization\\english\\event_localization\\death_events" "dif\\game\\localization\\english\\event_localization\\death_events" eu4
java -jar "tools\\LocaleParser\\bin\\LocaleParser-%parser_version%-SNAPSHOT.jar" "folder_diff" "orginal\\game\\localization\\english\\event_localization\\decisions" "nowe\\game\\localization\\english\\event_localization\\decisions" "dif\\game\\localization\\english\\event_localization\\decisions" eu4
java -jar "tools\\LocaleParser\\bin\\LocaleParser-%parser_version%-SNAPSHOT.jar" "folder_diff" "orginal\\game\\localization\\english\\event_localization\\experimental" "nowe\\game\\localization\\english\\event_localization\\experimental" "dif\\game\\localization\\english\\event_localization\\experimental" eu4
java -jar "tools\\LocaleParser\\bin\\LocaleParser-%parser_version%-SNAPSHOT.jar" "folder_diff" "orginal\\game\\localization\\english\\event_localization\\government_events" "nowe\\game\\localization\\english\\event_localization\\government_events" "dif\\game\\localization\\english\\event_localization\\government_events" eu4
java -jar "tools\\LocaleParser\\bin\\LocaleParser-%parser_version%-SNAPSHOT.jar" "folder_diff" "orginal\\game\\localization\\english\\event_localization\\lifestyle" "nowe\\game\\localization\\english\\event_localization\\lifestyle" "dif\\game\\localization\\english\\event_localization\\lifestyle" eu4
java -jar "tools\\LocaleParser\\bin\\LocaleParser-%parser_version%-SNAPSHOT.jar" "folder_diff" "orginal\\game\\localization\\english\\event_localization\\prison_events" "nowe\\game\\localization\\english\\event_localization\\prison_events" "dif\\game\\localization\\english\\event_localization\\prison_events" eu4
java -jar "tools\\LocaleParser\\bin\\LocaleParser-%parser_version%-SNAPSHOT.jar" "folder_diff" "orginal\\game\\localization\\english\\event_localization\\relation_events" "nowe\\game\\localization\\english\\event_localization\\relation_events" "dif\\game\\localization\\english\\event_localization\\relation_events" eu4
java -jar "tools\\LocaleParser\\bin\\LocaleParser-%parser_version%-SNAPSHOT.jar" "folder_diff" "orginal\\game\\localization\\english\\event_localization\\religion_events" "nowe\\game\\localization\\english\\event_localization\\religion_events" "dif\\game\\localization\\english\\event_localization\\religion_events" eu4
java -jar "tools\\LocaleParser\\bin\\LocaleParser-%parser_version%-SNAPSHOT.jar" "folder_diff" "orginal\\game\\localization\\english\\event_localization\\schemes" "nowe\\game\\localization\\english\\event_localization\\schemes" "dif\\game\\localization\\english\\event_localization\\schemes" eu4
java -jar "tools\\LocaleParser\\bin\\LocaleParser-%parser_version%-SNAPSHOT.jar" "folder_diff" "orginal\\game\\localization\\english\\event_localization\\secret_events" "nowe\\game\\localization\\english\\event_localization\\secret_events" "dif\\game\\localization\\english\\event_localization\\secret_events" eu4
java -jar "tools\\LocaleParser\\bin\\LocaleParser-%parser_version%-SNAPSHOT.jar" "folder_diff" "orginal\\game\\localization\\english\\event_localization\\story_cycles" "nowe\\game\\localization\\english\\event_localization\\story_cycles" "dif\\game\\localization\\english\\event_localization\\story_cycles" eu4
java -jar "tools\\LocaleParser\\bin\\LocaleParser-%parser_version%-SNAPSHOT.jar" "folder_diff" "orginal\\game\\localization\\english\\event_localization\\stress_events" "nowe\\game\\localization\\english\\event_localization\\stress_events" "dif\\game\\localization\\english\\event_localization\\stress_events" eu4
java -jar "tools\\LocaleParser\\bin\\LocaleParser-%parser_version%-SNAPSHOT.jar" "folder_diff" "orginal\\game\\localization\\english\\event_localization\\trait_specific_events" "nowe\\game\\localization\\english\\event_localization\\trait_specific_events" "dif\\game\\localization\\english\\event_localization\\trait_specific_events" eu4
java -jar "tools\\LocaleParser\\bin\\LocaleParser-%parser_version%-SNAPSHOT.jar" "folder_diff" "orginal\\game\\localization\\english\\event_localization\\yearly_events" "nowe\\game\\localization\\english\\event_localization\\yearly_events" "dif\\game\\localization\\english\\event_localization\\yearly_events" eu4
java -jar "tools\\LocaleParser\\bin\\LocaleParser-%parser_version%-SNAPSHOT.jar" "folder_diff" "orginal\\game\\localization\\english\\event_localization\\war_event" "nowe\\game\\localization\\english\\event_localization\\war_event" "dif\\game\\localization\\english\\event_localization\\war_event" eu4
java -jar "tools\\LocaleParser\\bin\\LocaleParser-%parser_version%-SNAPSHOT.jar" "folder_diff" "orginal\\game\\localization\\english\\event_localization\\lifestyle\\governance" "nowe\\game\\localization\\english\\event_localization\\lifestyle\\governance" "dif\\game\\localization\\english\\event_localization\\lifestyle\\governance" eu4
java -jar "tools\\LocaleParser\\bin\\LocaleParser-%parser_version%-SNAPSHOT.jar" "folder_diff" "orginal\\game\\localization\\english\\event_localization\\lifestyle\\guile" "nowe\\game\\localization\\english\\event_localization\\lifestyle\\guile" "dif\\game\\localization\\english\\event_localization\\lifestyle\\guile" eu4
java -jar "tools\\LocaleParser\\bin\\LocaleParser-%parser_version%-SNAPSHOT.jar" "folder_diff" "orginal\\game\\localization\\english\\event_localization\\lifestyle\\nickname" "nowe\\game\\localization\\english\\event_localization\\lifestyle\\nickname" "dif\\game\\localization\\english\\event_localization\\lifestyle\\nickname" eu4
java -jar "tools\\LocaleParser\\bin\\LocaleParser-%parser_version%-SNAPSHOT.jar" "folder_diff" "orginal\\game\\localization\\english\\event_localization\\lifestyle\\scholarship" "nowe\\game\\localization\\english\\event_localization\\lifestyle\\scholarship" "dif\\game\\localization\\english\\event_localization\\lifestyle\\scholarship" eu4
java -jar "tools\\LocaleParser\\bin\\LocaleParser-%parser_version%-SNAPSHOT.jar" "folder_diff" "orginal\\game\\localization\\english\\event_localization\\lifestyle\\statecraft" "nowe\\game\\localization\\english\\event_localization\\lifestyle\\statecraft" "dif\\game\\localization\\english\\event_localization\\lifestyle\\statecraft" eu4
java -jar "tools\\LocaleParser\\bin\\LocaleParser-%parser_version%-SNAPSHOT.jar" "folder_diff" "orginal\\game\\localization\\english\\event_localization\\lifestyle\\warfare" "nowe\\game\\localization\\english\\event_localization\\lifestyle\\warfare" "dif\\game\\localization\\english\\event_localization\\lifestyle\\warfare" eu4
java -jar "tools\\LocaleParser\\bin\\LocaleParser-%parser_version%-SNAPSHOT.jar" "folder_diff" "orginal\\game\\localization\\english\\event_localization\\councillor_task_events\\councillor_spouse_events" "nowe\\game\\localization\\english\\event_localization\\councillor_task_events\\councillor_spouse_events" "dif\\game\\localization\\english\\event_localization\\councillor_task_events\\councillor_spouse_events" eu4
java -jar "tools\\LocaleParser\\bin\\LocaleParser-%parser_version%-SNAPSHOT.jar" "folder_diff" "orginal\\game\\localization\\english\\event_localization\\schemes\\abduct" "nowe\\game\\localization\\english\\event_localization\\schemes\\abduct" "dif\\game\\localization\\english\\event_localization\\schemes\\abduct" eu4
java -jar "tools\\LocaleParser\\bin\\LocaleParser-%parser_version%-SNAPSHOT.jar" "folder_diff" "orginal\\game\\localization\\english\\event_localization\\schemes\\befriend" "nowe\\game\\localization\\english\\event_localization\\schemes\\befriend" "dif\\game\\localization\\english\\event_localization\\schemes\\befriend" eu4
java -jar "tools\\LocaleParser\\bin\\LocaleParser-%parser_version%-SNAPSHOT.jar" "folder_diff" "orginal\\game\\localization\\english\\event_localization\\schemes\\claim_throne" "nowe\\game\\localization\\english\\event_localization\\schemes\\claim_throne" "dif\\game\\localization\\english\\event_localization\\schemes\\claim_throne" eu4
java -jar "tools\\LocaleParser\\bin\\LocaleParser-%parser_version%-SNAPSHOT.jar" "folder_diff" "orginal\\game\\localization\\english\\event_localization\\schemes\\court" "nowe\\game\\localization\\english\\event_localization\\schemes\\court" "dif\\game\\localization\\english\\event_localization\\schemes\\court" eu4
java -jar "tools\\LocaleParser\\bin\\LocaleParser-%parser_version%-SNAPSHOT.jar" "folder_diff" "orginal\\game\\localization\\english\\event_localization\\schemes\\fabricate_hook" "nowe\\game\\localization\\english\\event_localization\\schemes\\fabricate_hook" "dif\\game\\localization\\english\\event_localization\\schemes\\fabricate_hook" eu4
java -jar "tools\\LocaleParser\\bin\\LocaleParser-%parser_version%-SNAPSHOT.jar" "folder_diff" "orginal\\game\\localization\\english\\event_localization\\schemes\\murder" "nowe\\game\\localization\\english\\event_localization\\schemes\\murder" "dif\\game\\localization\\english\\event_localization\\schemes\\murder" eu4
java -jar "tools\\LocaleParser\\bin\\LocaleParser-%parser_version%-SNAPSHOT.jar" "folder_diff" "orginal\\game\\localization\\english\\event_localization\\schemes\\seduce" "nowe\\game\\localization\\english\\event_localization\\schemes\\seduce" "dif\\game\\localization\\english\\event_localization\\schemes\\seduce" eu4
java -jar "tools\\LocaleParser\\bin\\LocaleParser-%parser_version%-SNAPSHOT.jar" "folder_diff" "orginal\\game\\localization\\english\\event_localization\\schemes\\sway" "nowe\\game\\localization\\english\\event_localization\\schemes\\sway" "dif\\game\\localization\\english\\event_localization\\schemes\\sway" eu4

::jomini
java -jar "tools\\LocaleParser\\bin\\LocaleParser-%parser_version%-SNAPSHOT.jar" "folder_diff" "orginal\\jomini\\localization" "nowe\\jomini\\localization" "dif\\jomini\\localization" eu4
java -jar "tools\\LocaleParser\\bin\\LocaleParser-%parser_version%-SNAPSHOT.jar" "folder_diff" "orginal\\jomini\\localization\\account" "nowe\\jomini\\localization\\account" "dif\\jomini\\localization\\account" eu4
java -jar "tools\\LocaleParser\\bin\\LocaleParser-%parser_version%-SNAPSHOT.jar" "folder_diff" "orginal\\jomini\\localization\\achievements" "nowe\\jomini\\localization\\achievements" "dif\\jomini\\localization\\achievements" eu4
java -jar "tools\\LocaleParser\\bin\\LocaleParser-%parser_version%-SNAPSHOT.jar" "folder_diff" "orginal\\jomini\\localization\\credits" "nowe\\jomini\\localization\\credits" "dif\\jomini\\localization\\credits" eu4
java -jar "tools\\LocaleParser\\bin\\LocaleParser-%parser_version%-SNAPSHOT.jar" "folder_diff" "orginal\\jomini\\localization\\frontend" "nowe\\jomini\\localization\\frontend" "dif\\jomini\\localization\\frontend" eu4
java -jar "tools\\LocaleParser\\bin\\LocaleParser-%parser_version%-SNAPSHOT.jar" "folder_diff" "orginal\\jomini\\localization\\jomini" "nowe\\jomini\\localization\\jomini" "dif\\jomini\\localization\\jomini" eu4
java -jar "tools\\LocaleParser\\bin\\LocaleParser-%parser_version%-SNAPSHOT.jar" "folder_diff" "orginal\\jomini\\localization\\pops" "nowe\\jomini\\localization\\pops" "dif\\jomini\\localization\\pops" eu4
java -jar "tools\\LocaleParser\\bin\\LocaleParser-%parser_version%-SNAPSHOT.jar" "folder_diff" "orginal\\jomini\\localization\\settings" "nowe\\jomini\\localization\\settings" "dif\\jomini\\localization\\settings" eu4
java -jar "tools\\LocaleParser\\bin\\LocaleParser-%parser_version%-SNAPSHOT.jar" "folder_diff" "orginal\\jomini\\localization\\social" "nowe\\jomini\\localization\\social" "dif\\jomini\\localization\\social" eu4
::jomini\\jomini
java -jar "tools\\LocaleParser\\bin\\LocaleParser-%parser_version%-SNAPSHOT.jar" "folder_diff" "orginal\\jomini\\localization\\jomini\\coat_of_arms" "nowe\\jomini\\localization\\jomini\\coat_of_arms" "dif\\jomini\\localization\\jomini\\coat_of_arms" eu4
java -jar "tools\\LocaleParser\\bin\\LocaleParser-%parser_version%-SNAPSHOT.jar" "folder_diff" "orginal\\jomini\\localization\\jomini\\multiplayer_gui" "nowe\\jomini\\localization\\jomini\\multiplayer_gui" "dif\\jomini\\localization\\jomini\\multiplayer_gui" eu4
java -jar "tools\\LocaleParser\\bin\\LocaleParser-%parser_version%-SNAPSHOT.jar" "folder_diff" "orginal\\jomini\\localization\\jomini\\script_system" "nowe\\jomini\\localization\\jomini\\script_system" "dif\\jomini\\localization\\jomini\\script_system" eu4
::clausewitz
java -jar "tools\\LocaleParser\\bin\\LocaleParser-%parser_version%-SNAPSHOT.jar" "folder_diff" "orginal\\clausewitz\\localization" "nowe\\clausewitz\\localization" "dif\\clausewitz\\localization" eu4
java -jar "tools\\LocaleParser\\bin\\LocaleParser-%parser_version%-SNAPSHOT.jar" "folder_diff" "orginal\\clausewitz\\localization\\text_utils" "nowe\\clausewitz\\localization\\text_utils" "dif\\clausewitz\\localization\\text_utils" eu4

::dlc
java -jar "tools\\LocaleParser\\bin\\LocaleParser-%parser_version%-SNAPSHOT.jar" "folder_diff" "orginal\\game\\localization\\english\\dlc\\fp1" "nowe\\game\\localization\\english\\dlc\\fp1" "dif\\game\\localization\\english\\dlc\\fp1" eu4

pause

:::::::: DO POPRAWY, 