l_polish:
 SETTING_REFRACTION:0 "Refrakcja"
 SETTING_REFRACTION_QUALITY:0 "Jakość refrakcji"
 SETTING_MAPOBJECT_QUALITY:0 "Obiekty na mapie"
 SETTING_MAP_SSAO:0 "Mapa – SSAO"
 SETTING_DOF:0 "Głębia ostrości"
 SETTING_LENS_FLARE:0 "Flara obiektywu"
 SETTING_SECONDARY_LENS_FLARE:0 "Dodatkowa flara obiektywu"
