l_polish:
 SETTINGS_PAGE_GRAPHICS: ""
 SETTINGS_PAGE_GAME: ""
 SETTINGS_PAGE_SYSTEM: ""
 SETTINGS_PAGE_CONTROLS: ""
 SETTINGS_PAGE_EDITOR: ""
 SETTINGS_PAGE_INTERFACE: ""
 SETTINGS_PAGE_AUDIO: ""
 SETTINGS_CATEGORY_SCREEN: ""
 SETTINGS_CATEGORY_QUALITY: ""
 OPTION_EASY: ""
 OPTION_NORMAL: ""
 OPTION_HARD: ""
 OPTION_NEVER: ""
 OPTION_MONTHLY: ""
 OPTION_HALFYEAR: ""
 OPTION_YEARLY: ""
 OPTION_FIVE_YEAR: ""
 OPTION_NO_AUTOSAVE: ""
 SETTINGS_CATEGORY_ACCOUNT: ""
 SETTINGS_CATEGORY_SYSTEM: ""
 SETTINGS_CATEGORY_CONTROLS: ""
 SETTINGS_CATEGORY_CAMERA: ""
 SETTINGS_CATEGORY_AUDIO: ""
 SETTINGS_CATEGORY_GUI: ""
 SETTINGS_CATEGORY_INPUT_BINDINGS: ""
 DISCARD: ""
 SAVE_AND_CLOSE: ""
 SETTINGS: ""
 REQUIRES_RESTART: ""
 REQUIRE_RESTART_DESCRIPTION: ""
 SETTINGS_INPUT_REMAP_INPUT: ""
 SETTINGS_INPUT_CONFIRM: ""
 SETTINGS_INPUT_CANCEL: ""
 SETTINGS_INPUT_CLEAR: ""
 SETTINGS_INPUT_SAVE_INPUT_PROFILE: ""
 SETTINGS_INPUT_LOAD_INPUT_PROFILE: ""
 SETTINGS_INPUT_RESET_INPUT_PROFILE: ""
 SETTINGS_INPUT_BINDING_TEXT: ""
 SETTINGS_INPUT_BINDING_WARNING_TEXT: ""
