l_polish:
 SETTING_VALUE_NONE: "$VALUE$"
 SETTING_VALUE_TOTAL_PERCENTAGE: "$VALUE|%/0$"
 SETTING_VALUE_PERCENTAGE: "$VALUE|%0$"
 SETTING_VALUE_SECONDS: "$VALUE$ s"
 SETTING_VALUE_MINUTES: "$VALUE$ min"
 SETTING_RENDERER: "Mechanizm renderujący"
 SETTING_VSYNC: "Synchronizacja pionowa"
 SETTING_VSYNC_TOOLTIP: "#T $SETTING_VSYNC$\n#!Włączenie synchronizacji pionowej powoduje wyrównanie liczby klatek na sekundę w przypadku gry i monitora, co redukuje efekt rozchodzenia się obrazu.\n\nWyłączenie tej funkcji może poprawić wydajność."
 SETTING_PORTRAIT_MULTI_SAMPLING: "Wielokrotne próbkowanie portretów"
 SETTING_PORTRAIT_MULTI_SAMPLING_TOOLTIP: "#T $SETTING_PORTRAIT_MULTI_SAMPLING$\n#!Włączenie funkcji wielokrotnego próbkowania w przypadku techniki Alpha-To-Coverage (zamiana mieszania alfa na maskę kryjącą) powoduje wygładzenie włosów postaci.\n\nNiższe ustawienia zwiększają wydajność."
 SETTING_MULTI_SAMPLING: "Wygładzanie krawędzi (MSAA)"
 SETTING_MULTI_SAMPLING_TOOLTIP: "#T $SETTING_MULTI_SAMPLING$\n#!Włączenie funkcji wielopróbkowego wygładzania krawędzi (MSAA) sprawi, że krawędzie obrazów będą gładsze.\n\nNiższe ustawienia mogą zwiększyć wydajność."
 SETTING_ANTI_ALIASING: "Wygładzanie krawędzi"
 SETTING_ANTI_ALIASING_TOOLTIP: "#T $SETTING_ANTI_ALIASING$\n#!Włączenie funkcji wygładzania krawędzi sprawi, że krawędzie obrazów będą gładsze.\n\nZalecane jest wybranie opcji FXAA."
 OPTION_ANTI_ALIASING_DISABLED: "Wył."
 OPTION_ANTI_ALIASING_FXAA: "FXAA"
 SETTING_ANISOTROPIC_FILTERING: "Filtrowanie tekstur"
 SETTING_ANISOTROPIC_FILTERING_TOOLTIP: "#T $SETTING_ANISOTROPIC_FILTERING$\n#!Włączenie funkcji filtrowania anizotropowego poprawi wygląd tekstur powierzchni.\n\nNiższe ustawienia mogą zwiększyć wydajność."
 SETTING_FULLSCREEN_RESOLUTION: "Rozdzielczość"
 SETTING_FULLSCREEN_RESOLUTION_TOOLTIP: "#T $SETTING_FULLSCREEN_RESOLUTION$\n#!Opcja ta wpływa na jakość obrazu w grze.\n\nNiższa rozdzielczość może zwiększyć wydajność.\n\n#X Wybranie rozdzielczości o nieobsługiwanych wymiarach obrazu może spowodować wyświetlanie się interfejsów poza ekranem.#!"
 SETTING_WINDOWED_RESOLUTION: "Rozdzielczość w trybie okna"
 SETTING_WINDOWED_RESOLUTION_TOOLTIP: "#T $SETTING_WINDOWED_RESOLUTION$\n#!Funkcja ta umożliwia określenie rozdzielczości gry w trybie okna.\n\nWymagany format to #b LICZBA#!×#b LICZBA#!.\n\n#X Wybranie rozdzielczości o nieobsługiwanych wymiarach obrazu może spowodować wyświetlanie się interfejsów poza ekranem.#!"
 SETTING_RENDER_SCALE: "Skala renderowania"
 SETTING_RENDER_SCALE_TOOLTIP: "#T $SETTING_RENDER_SCALE$#!\nSkala rozdzielczości renderowania w grze związana z rozdzielczością główną. Nie dotyczy interfejsu użytkownika.\n\nNiższe ustawienia mogą zwiększyć wydajność, ale spowodują zmniejszenie ogólnej wierności obrazu. Przekroczenie wartości 100% może z kolei zwiększyć wierność obrazu, ale prawdopodobnie spowoduje spadek wydajności."
 SETTING_RENDER_SCALE_FORMAT: "$VALUE|%0$"
 SETTING_DISPLAY: "Monitor"
 SETTING_DISPLAY_TOOLTIP: "#T $SETTING_DISPLAY$\n#!Jeżeli do twojego komputera podłączony jest więcej niż jeden monitor, wybierz ten, na którym ma być wyświetlana gra."
 SETTING_GRAPHICS_DEVICE: "Karta graficzna"
 SETTING_GRAPHICS_DEVICE_TOOLTIP: "#T $SETTING_GRAPHICS_DEVICE$\n#!Wybierz kartę graficzną, z której ma korzystać gra. \n\nKorzystanie ze zintegrowanej karty graficznej lub oprogramowania renderującego może zmniejszyć wydajność."
 SETTING_SHADOW_MAP_RESOLUTION: "Jakość cieni"
 SETTING_SHADOW_MAP_RESOLUTION_TOOLTIP: "#T $SETTING_SHADOW_MAP_RESOLUTION$\n#!Funkcja ta pozwala określić rozdzielczość renderowania w przypadku mapowania cieni, jeśli cienie są włączone.\n\nNiższe ustawienia mogą zwiększyć wydajność."
 SETTING_DISPLAY_MODE: "Tryb wyświetlania"
 SETTING_DISPLAY_MODE_TOOLTIP: "#T $SETTING_DISPLAY_MODE$\n#!Funkcja ta pozwala określić sposób wyświetlania gry na ekranie."
 SETTING_BLOOM: "Rozmycie"
 SETTING_MESH_LOD_BIAS: "Jakość szczegółów siatki"
 SETTING_MESH_LOD_FADE: "Zanikanie szczegółów siatki"
 SETTING_TERRAIN_SMOOTHING: "Wygładzanie terenu"
 OPTION_FULLSCREEN: "Pełny ekran"
 OPTION_FULLSCREEN_TOOLTIP: "#T $OPTION_FULLSCREEN$\n#!Wybranie tego trybu powoduje wyświetlenie gry na pełnym ekranie. Ostrość obrazu zależy od wybranej rozdzielczości."
 OPTION_WINDOWED: "Okno"
 OPTION_WINDOWED_TOOLTIP: "#T $OPTION_WINDOWED$\n#!Wybranie tego trybu powoduje wyświetlenie gry w oknie. Rozmiar okna zależy od wybranej rozdzielczości."
 OPTION_DISABLED: "Wył."
 OPTION_OFF: "Wył."
 OPTION_LOW: "Niska"
 OPTION_MEDIUM: "Średnia"
 OPTION_HIGH: "Wysoka"
 OPTION_ULTRA: "Ultra"
 OPTION_CUSTOM: "Niestandardowa"
 OPTION_DEFAULT: "Domyślnie"
 SETTINGS_CATEGORY_UI: "Interfejs"
 SETTINGS_CATEGORY_GAME: "Gra"
 SETTING_TEXTURE_QUALITY: "Jakość tekstur"
 SETTING_TEXTURE_QUALITY_TOOLTIP: "#T $SETTING_TEXTURE_QUALITY$#!\nOpcja ta wpływa na rozdzielczość wczytywanych tekstur.\n\nNiższe ustawienia mogą zwiększyć wydajność."
 SETTING_QUALITY: "Ustawienie wstępne jakości"
 SETTING_SFX: "Efekty specjalne"
 SETTING_UI: "Interfejs"
 SETTING_QUALITY_TOOLTIP: "#T $SETTING_QUALITY$\n#!Wybierz jedno z poniższych ustawień wstępnych dotyczących zaawansowanych opcji grafiki.\n\nNiskie ustawienie wstępne zwiększy wydajność."
 SETTING_BLOOM_TOOLTIP: "#T $SETTING_BLOOM$\n#!Włączenie tej funkcji powoduje zastosowanie efektu rozmycia, który sprawia, że bardzo jasne światła wpływają na inne części obrazu.\n\nWyłączenie jej może zwiększyć wydajność."
 SETTING_DOF_TOOLTIP: "#T $SETTING_DOF$\n#!Funkcja głębi ostrości imituje działanie obiektywu, powodując rozmycie obrazu poza punktem ostrości.\n\nWyłączenie jej może zwiększyć wydajność."
 SETTING_MAP_SSAO_TOOLTIP: "#T $SETTING_MAP_SSAO$\n#!Ustawienie to umożliwia włączenie lub wyłączenie funkcji okluzji otoczenia w przestrzeni ekranu w przypadku mapy.\n\nWyłączenie jej może zwiększyć wydajność."
 SETTING_REFRACTION_TOOLTIP: "Ustawienie to umożliwia włączenie lub wyłączenie odbić na powierzchni wody."
 SETTING_REFRACTION_QUALITY_TOOLTIP: "#T $SETTING_REFRACTION_QUALITY$#!\nUstawienia te wpływają na jakość odbić na powierzchni wody, jeśli odbicia są włączone.\n\nNiższe ustawienia mogą zwiększyć wydajność."
 SETTING_MAPOBJECT_QUALITY_TOOLTIP: "#T $SETTING_MAPOBJECT_QUALITY$#!\nUstawienia te pozwalają określić najwyższy poziom jakości obiektów na mapie, takich jak budynki.\n\nNiższe ustawienia mogą zwiększyć wydajność."
 SETTING_MESH_LOD_BIAS_TOOLTIP: "#T $SETTING_MESH_LOD_BIAS$#!\nUstawienia te pozwalają określić jakość szczegółów obiektów widocznych na mapie, takich jak modele jednostek.\n\nNiższe ustawienia mogą zwiększyć wydajność."
 SETTING_MESH_LOD_FADE_TOOLTIP: "#T $SETTING_MESH_LOD_FADE$\n#!Włączenie tej opcji umożliwia płynną zmianę poziomów szczegółowości modeli trójwymiarowych podczas przybliżania i oddalania widoku.\n\nWyłączenie tej opcji może zwiększyć wydajność."
 SETTING_PROVINCE_NAMES_TOOLTIP: "Ustawienie to pozwala określić sposób wyświetlania nazw miast i prowincji na mapie."
 SETTING_FILL_IN_IMPASSABLE_TERRAIN_TOOLTIP: "Ustawienie to pozwala określić, czy granice państwa na mapie mają uwzględniać tereny nie do przebycia."
 SETTING_LANGUAGE_TOOLTIP: "#T $SETTING_LANGUAGE$#!\nUstawienie to umożliwia wybór języka interfejsu użytkownika."
 SETTING_ACCOUNT_EMAIL_TOOLTIP: "Twój adres e-mail konta Paradox"
 SETTING_FRAMERATE_CAP: "Limit klatek na sekundę"
 SETTING_FRAMERATE_CAP_TOOLTIP: "#T $SETTING_FRAMERATE_CAP$#!\nUstawienia te pozwalają określić maksymalną liczbę klatek na sekundę renderowanych przez grę.\n\nNiższe ustawienia mogą zmniejszyć zużycie energii."
 OPTION_CAP_30: "30"
 OPTION_CAP_60: "60"
 OPTION_CAP_90: "90"
 OPTION_CAP_120: "120"
 OPTION_CAP_144: "144"
 OPTION_CAP_165: "165"
 SETTING_TEXTURE_STREAMING: "Przesyłanie tekstur"
 SETTING_TEXTURE_STREAMING_CACHE: "Przesyłanie tekstur – ilość miejsca w pamięci podręcznej"
 SETTING_VALUE_MB: "$VALUE$ MB"
 SETTING_ANIMATION_SPEED: "Szybkość animacji"
 SETTING_GUI_SCALING: "Skalowanie graficznego interfejsu użytkownika"
 SETTING_GUI_SCALING_TOOLTIP: "#T $SETTING_GUI_SCALING$\n#!Funkcja ta wpływa na skalę całego interfejsu użytkownika. Przydaje się przy wyższych rozdzielczościach ekranu.\n\n#X Ustawienie zbyt wysokiej wartości sprawi, że interfejsy nie będą mieścić się na ekranie.#!"
 SETTING_SCREEN_EDGE_SCROLL_MODE: "Przesuwanie ekranu myszą"
 SETTING_SCREEN_EDGE_SCROLL_MODE_FREE: "Swobodne"
 SETTING_SCREEN_EDGE_SCROLL_MODE_8_DIRECTIONS: "8-kierunkowe"
 SETTING_SCREEN_EDGE_SCROLL_DISABLED: "Wył."
 SETTING_SCREEN_EDGE_SCROLL_MODE_TOOLTIP: "#T $SETTING_SCREEN_EDGE_SCROLL_MODE$#!\nFunkcja ta pozwala określić zachowanie kamery podczas przesuwania ekranu myszą."
 SETTING_SCROLL_SPEED: "Szybkość przesuwania"
 SETTING_SCROLL_SPEED_TOOLTIP: "#T $SETTING_SCROLL_SPEED$#!\nFunkcja ta pozwala określić szybkość przesuwania mapy za pomocą klawiatury lub myszy."
 SETTING_CAMERA_ROTATION_SPEED: "Szybkość obrotu kamery"
 SETTING_CAMERA_ROTATION_SPEED_TOOLTIP: "#T $SETTING_CAMERA_ROTATION_SPEED$#!\nFunkcja ta pozwala określić szybkość obrotu kamery."
 SETTING_ZOOM_SPEED: "Szybkość przybliżania"
 SETTING_ZOOM_SPEED_TOOLTIP: "#T $SETTING_ZOOM_SPEED$#!\nFunkcja ta pozwala określić szybkość przybliżania."
 SETTING_MOUSE_CURSOR_ZOOM_MODE: "Zachowanie podczas przybliżania"
 SETTING_MOUSE_CURSOR_ZOOM_MODE_RELATIVE_CURSOR: "Kursor względny"
 SETTING_MOUSE_CURSOR_ZOOM_MODE_ZOOM_IN_TO_CURSOR: "Przybliżenie na kursor"
 SETTING_MOUSE_CURSOR_ZOOM_MODE_IGNORE_CURSOR: "Ignorowanie kursora"
 SETTING_MOUSE_CURSOR_ZOOM_MODE_TOOLTIP: "#T $SETTING_MOUSE_CURSOR_ZOOM_MODE$#!\nFunkcja ta pozwala określić sposób zachowania kamery względem kursora podczas przybliżania/oddalania."
 SETTING_INPUT_DEVICE: "Urządzenie wejściowe"
 SETTING_EDITOR: "Edytor"
 SETTING_EDITOR_POSTFIX: "Edytor – postfiks"
 SETTING_EDITOR_OPEN_FILE_FORMAT: "Komenda otwarcia edytora"
 SETTING_LOG_VIEWER_OPEN_FILE_FORMAT: "Komenda wyświetlenia rejestru"
 SETTING_CODE_EDITOR_OPEN_FILE_FORMAT: "Komenda otwarcia edytora kodu"
 SETTING_GRACEFUL_EXIT: "Wyjście z klasą"
 SETTING_LANGUAGE: "Język"
 MOUSE_AND_KEYBOARD: "Mysz i klawiatura"
 GAMEPAD: "Kontroler"
 SETTING_MULTISAMPLING_DISABLED: "Wył."
 SETTING_PORTRAIT_MULTISAMPLING_DISABLED: "Wył."
 SETTING_ANISOTROPIC_FILTERING_DISABLED: "Wył."
 SETTING_CAMERA_TILT: "Przechylenie kamery"
 SETTING_CAMERA_STRATEGY: "Rodzaj kamery"
 SETTING_CENTERED_ZOOM_IN: "Wyśrodkowane przybliżenie"
 SETTING_CAMERA_SPEED: "Szybkość kamery"
 CAMERA_TABLETOP: "Rzut z góry"
 CAMERA_FPS: "Widok pierwszoosobowy"
 CAMERA_WASD: "Styl WASD"
 SETTING_Music: "Muzyka"
 SETTING_Ambient: "Dźwięki otoczenia"
 SETTING_Effects: "Efekty"
 SETTING_Master: "Głośność ogólna"
 SETTING_Master_TOOLTIP: "#T Głośność ogólna\n#!Ustawienie to wpływa na głośność wszystkich dźwięków w grze."
 SETTING_Music_TOOLTIP: "#T Głośność muzyki\n#!Ustawienie to wpływa na głośność muzyki."
 SETTING_Ambient_TOOLTIP: "#T Głośność dźwięków otoczenia\n#!Ustawienie to wpływa na głośność dźwięków otoczenia."
 SETTING_SFX_TOOLTIP: "#T Głośność efektów specjalnych\n#!Ustawienie to wpływa na głośność efektów dźwiękowych takich jak odgłosy walki."
 SETTING_UI_TOOLTIP: "#T Głośność interfejsu\n#!Ustawienie to wpływa na głośność interfejsu użytkownika."
 SETTING_AUDIO_DEBUG_LOG_LEVEL: "Poziom rejestru debugowania"
 SETTING_AUDIO_DEVICE_PROFILE: "Profil dźwiękowy"
 SETTING_AUDIO_DEVICE_PROFILE_TOOLTIP: "#T $SETTING_AUDIO_DEVICE_PROFILE$\n#!Wybierz profil dźwiękowy, który najlepiej odpowiada twojej konfiguracji."
 SETTING_AUDIO_OPTION_SPEAKERS: "Głośniki"
 SETTING_AUDIO_OPTION_SPEAKERS_TOOLTIP: "#T $SETTING_AUDIO_OPTION_SPEAKERS$\n#!Miks domyślny ($SETTING_AUDIO_OPTION_SPEAKERS$)."
 SETTING_AUDIO_OPTION_HEADPHONES: "Słuchawki"
 SETTING_AUDIO_OPTION_HEADPHONES_TOOLTIP: "#T $SETTING_AUDIO_OPTION_HEADPHONES$\n#!Miks dostosowany do urządzenia ($SETTING_AUDIO_OPTION_HEADPHONES$)."
 SETTING_AUDIO_OPTION_TV: "Telewizor"
 SETTING_AUDIO_OPTION_TV_TOOLTIP: "#T $SETTING_AUDIO_OPTION_TV$\n#!Miks dostosowany do urządzenia ($SETTING_AUDIO_OPTION_TV$ i głośniki monitora)."
 SETTING_AUDIO_OPTION_NIGHTMODE: "Tryb nocny"
 SETTING_AUDIO_OPTION_NIGHTMODE_TOOLTIP: "#T $SETTING_AUDIO_OPTION_NIGHTMODE$\n#!Wybranie tego ustawienia powoduje wyciszenie dźwięków obejmujące przytłumienie wysokich tonów i ograniczenie zakresu dynamicznego, co ułatwia rozgrywkę w nocy."
 SETTING_MUSIC_DENSITY: "Częstotliwość muzyki"
 SETTING_MUSIC_DENSITY_TOOLTIP: "Ta opcja umożliwia kontrolę balansu między kompletnymi utworami, ciszą a nastrojowymi segmentami muzycznymi. \n\nDuża intensywność – jeśli wybierzesz tę opcję, odtwarzane będą głównie utwory, jeden po drugim – jak w radiu. \nŚrednia intensywność – ta opcja zapewnia idealną równowagę między utworami, ciszą i nastrojową oprawą muzyczną. \nMała intensywność – odtwarzane będą głównie relaksujące segmenty muzyczne, które zapewniają bardziej stonowane wrażenia i pozwalają uniknąć powtarzalności po kilku godzinach rozgrywki"
 SETTING_AUTOSAVE: "Interwał automatycznego zapisu"
 SETTING_AUTOSAVE_TOOLTIP: "#T $SETTING_AUTOSAVE$\n#!Ustawienie to pozwala określić częstotliwość automatycznego zapisu gry."
 SETTING_AUTOSAVE_TO_CLOUD_TOOLTIP: "Ustawienie to pozwala określić, czy automatyczne zapisy mają być przechowywane w chmurze."
 SETTING_CAMERA_FACE_NORTH_TOOLTIP: "Ustawienie to pozwala określić, czy kamera ma być zawsze skierowana na północ."
 NO_AUTOSAVE: "Brak automatycznego zapisu"
 SETTINGS_FILE_TRANSFER_SPEED: "Prędkość przesyłania plików"
 SETTINGS_FILE_TRANSFER_SPEED_TOOLTIP: "#T Prędkość przesyłania plików\n#!Ustawienie to pozwala określić maksymalną prędkość przesyłania pliku z zapisanym stanem gry w lobby w trybie wieloosobowym.\n\nNiższe ustawienia mogą zwiększyć stabilność sieci podczas dołączania do gier w trybie wieloosobowym, ale wydłużają czas wczytywania trybu wieloosobowego."
 SETTING_MAP_EDITOR_AUTOSAVE_INTERVAL_MINUTES: "Automatyczny zapis w edytorze mapy (w minutach)"
 SETTING_MAP_EDITOR_AUTOSAVE_INTERVAL_MINUTES_TOOLTIP: "Interwał automatycznego zapisu w edytorze mapy (w minutach)"
 SETTING_NODE_EDITOR_DRAG_PAN_MODE: "Tryb przesuwania ekranu podczas przeciągania w edytorze węzłów"
 SETTINGS_CATEGORY_ACCESSIBILITY: "Ułatwienia dostępu"
 SETTING_COLOR_BLIND_MODE: "Tryb dla osób ze ślepotą barw"
 SETTING_COLOR_BLIND_MODE_TOOLTIP: "#T $SETTING_COLOR_BLIND_MODE$\n#!Funkcja ta umożliwia zmianę kolorów tekstów w grze, ułatwiając ich rozróżnianie osobom z różnymi rodzajami ślepoty barw."
