l_polish:
 SETTING_INPUT_CONTEXT_COMMON: ""
 SETTING_INPUT_CONTEXT_COMMON_TOOLTIP: ""
 SETTING_INPUT_ACTION_PAUSE: ""
 SETTING_INPUT_ACTION_INCREASE_SPEED: ""
 SETTING_INPUT_ACTION_DECREASE_SPEED: ""
 SETTING_INPUT_ACTION_SPEED_ONE: ""
 SETTING_INPUT_ACTION_SPEED_TWO: ""
 SETTING_INPUT_ACTION_SPEED_THREE: ""
 SETTING_INPUT_ACTION_SPEED_FOUR: ""
 SETTING_INPUT_ACTION_SPEED_FIVE: ""
 SETTING_INPUT_ACTION_PLAY_PAUSE_MUSIC: ""
 SETTING_INPUT_ACTION_NEXT_MUSIC_TRACK: ""
 SETTING_INPUT_ACTION_CAMERA_UP: ""
 SETTING_INPUT_ACTION_CAMERA_LEFT: ""
 SETTING_INPUT_ACTION_CAMERA_DOWN: ""
 SETTING_INPUT_ACTION_CAMERA_RIGHT: ""
 SETTING_INPUT_ACTION_LOCATION_FINDER: ""
 SETTING_INPUT_ACTION_OPEN_POLITICS: ""
 SETTING_INPUT_ACTION_OPEN_BUDGET: ""
 SETTING_INPUT_ACTION_OPEN_BUILDINGS: ""
 SETTING_INPUT_ACTION_OPEN_MARKET: ""
 SETTING_INPUT_ACTION_OPEN_MILITARY: ""
 SETTING_INPUT_ACTION_OPEN_DIPLOMATIC: ""
 SETTING_INPUT_ACTION_OPEN_TECHNOLOGY: ""
 SETTING_INPUT_ACTION_OPEN_CULTURE: ""
 SETTING_INPUT_ACTION_OPEN_POPULATION: ""
 SETTING_INPUT_ACTION_OPEN_JOURNAL: ""
 SETTING_INPUT_ACTION_OPEN_POWER_BLOC: ""
 SETTING_INPUT_ACTION_OPEN_COMPANIES: ""
 SETTING_INPUT_ACTION_MAP_LIST: ""
 SETTING_INPUT_ACTION_BACK: ""
 SETTING_INPUT_ACTION_OPEN_OUTLINER: ""
 SETTING_INPUT_ACTION_TAB_1: ""
 SETTING_INPUT_ACTION_TAB_2: ""
 SETTING_INPUT_ACTION_TAB_3: ""
 SETTING_INPUT_ACTION_TAB_4: ""
 SETTING_INPUT_ACTION_TAB_5: ""
 SETTING_INPUT_ACTION_PRODUCTION_LENS: ""
 SETTING_INPUT_ACTION_POLITICAL_LENS: ""
 SETTING_INPUT_ACTION_DIPLOMATIC_LENS: ""
 SETTING_INPUT_ACTION_MILITARY_LENS: ""
 SETTING_INPUT_ACTION_TRADE_LENS: ""
 SETTING_INPUT_ACTION_CONFIRM: ""
 SETTING_INPUT_ACTION_CURRENT_SITUATION: ""
 SETTING_INPUT_ACTION_CONSTRUCTION_QUEUE: ""
 SETTING_INPUT_ACTION_TOGGLE_CONSTRUCTION_QUEUE_PAUSE: ""
 SETTING_INPUT_ACTION_GO_TO_DETAILS: ""
 SETTING_INPUT_ACTION_SCROLL_UP: ""
 SETTING_INPUT_ACTION_SCROLL_DOWN: ""
 SETTING_INPUT_ACTION_TOGGLE_GUI_DEBUG: ""
 SETTING_INPUT_ACTION_OUTLINER_TOGGLE_PINNED: ""
 SETTING_INPUT_ACTION_OUTLINER_TOGGLE_ECONOMY: ""
 SETTING_INPUT_ACTION_OUTLINER_TOGGLE_POLITICS: ""
 SETTING_INPUT_ACTION_OUTLINER_TOGGLE_DIPLOMACY: ""
 SETTING_INPUT_ACTION_OUTLINER_TOGGLE_MILITARY: ""
 SETTING_INPUT_ACTION_OUTLINER_TOGGLE_ALL: ""
 SETTING_INPUT_ACTION_TOGGLE_PIN: ""
 SETTING_INPUT_ACTION_ZOOM_TO: ""
