l_polish:
 pm_primary: ""
 pmg_secondary_building_rye_farm: ""
 pmg_secondary_building_wheat_farm: ""
 pmg_secondary_building_rice_farm: ""
 pmg_secondary_building_maize_farm: ""
 pmg_secondary_building_millet_farm: ""
 pm_no_secondary: ""
 pm_potatoes: ""
 pm_vineyards: ""
 pm_vineyards_building_maize_farm: ""
 pm_apple_orchards: ""
 pm_citrus_orchards: ""
 pm_fig_orchards: ""
 pm_fig_orchards_building_rice_farm: ""
 pm_mulberry_groves: ""
 pmg_automation: ""
 pmg_automation_building_food_industry: ""
 pmg_automation_building_textile_mills: ""
 pmg_automation_building_furniture_manufacturies: ""
 pmg_automation_building_tooling_workshops: ""
 pmg_automation_building_paper_mills: ""
 pmg_automation_building_steel_mills: ""
 pmg_automation_building_motor_industry: ""
 pmg_automation_building_automotive_industry: ""
 pm_civilian_priority: ""
 pm_military_priority: ""
 pm_craftsman_sewing: ""
 pm_sewing_machines: ""
 pm_electric_sewing_machines: ""
 pm_traditional_looms: ""
 pm_mechanized_looms: ""
 pm_automatic_power_looms: ""
 pm_leaded_glass: ""
 pm_manual_glassblowing: ""
 pm_leblanc_process: ""
 pm_no_explosives_production: ""
 pm_ammonia-soda_process: ""
 pm_vacuum_evaporation: ""
 pm_brine_electrolysis: ""
 pmg_fertilizer_production: ""
 pm_no_artificial_fertilizers: ""
 pm_artificial_fertilizers: ""
 pm_improved_fertilizer: ""
 pm_nitrogen_fixation: ""
 pm_dyes_production: ""
 pm_no_synthetic_dyes: ""
 pmg_synthetic_dyes: ""
 pm_silk_production: ""
 pm_no_artificial_fibers: ""
 pm_rayon: ""
 pm_steamworks: ""
 pm_no_artillery_production: ""
 pm_artillery_production: ""
 pmg_automobile_production: ""
 pm_automobile_production: ""
 pm_mass_automobile_production: ""
