l_polish:
 SETTING_AUTOSAVE_TO_CLOUD: ""
 SETTING_SAVE_FILE_FORMAT: ""
 SETTING_SAVE_FILE_FORMAT_TOOLTIP: ""
 OPTION_SAVE_FILE_TEXT: ""
 OPTION_SAVE_FILE_ZIP_TEXT_ALL: ""
 OPTION_SAVE_FILE_ZIP_BINARY_ALL: ""
 SETTING_TOOLTIP_MODE: ""
 SETTING_TOOLTIP_MODE_TOOLTIP: ""
 SETTING_TOOLTIP_MODE_NO_LOCK: ""
 SETTING_TOOLTIP_MODE_MOUSE_TENDENCY: ""
 SETTING_TOOLTIP_MODE_LOCK_ON_ACTION_MOUSE_ANCHOR: ""
 SETTING_TOOLTIP_MODE_LOCK_ON_TIMER_MOUSE_ANCHOR: ""
 SETTING_TOOLTIP_MODE_LOCK_ON_ACTION_WIDGET_ANCHOR: ""
 SETTING_TOOLTIP_MODE_LOCK_ON_TIMER_WIDGET_ANCHOR: ""
 SETTING_TOOLTIP_MODE_LOCK_ON_TIMER_OR_ACTION_WIDGET_ANCHOR: ""
 SETTING_TOOLTIP_DELAY_TOOLTIP: ""
 SETTING_TOOLTIP_DELAY: ""
 SETTING_TOOLTIP_UNLOCK_TIME: ""
 SETTING_TOOLTIP_UNLOCK_TIME_TOOLTIP: ""
 SETTING_TOOLTIP_LOCK_TIME: ""
 SETTING_TOOLTIP_LOCK_TIME_TOOLTIP: ""
 SETTING_TOOLTIP_OPEN_TIME_WHEN_ANOTHER_LOCKED: ""
 SETTING_TOOLTIP_OPEN_TIME_WHEN_ANOTHER_LOCKED_TOOLTIP: ""
 SETTINGS_CATEGORY_ADVANCED_GRAPHICS: ""
 SETTINGS_CATEGORY_AUDIO_GENERAL: ""
 SETTINGS_CATEGORY_SFX: ""
 SETTINGS_CATEGORY_MFX: ""
 SETTINGS_CATEGORY_LANGUAGE: ""
 SETTINGS_CATEGORY_SAVE_GAMES: ""
 SETTINGS_CATEGORY_TOOLTIPS: ""
 SETTINGS_CATEGORY_OUTLINER: ""
 SETTINGS_CATEGORY_MAP_CONTROLS: ""
 SETTINGS_CATEGORY_MAPMODES: ""
 SETTING_SHADER_QUALITY: ""
 SETTING_SHADER_QUALITY_TOOLTIP: ""
 SETTING_SHOW_NUDITY: ""
 SETTING_SHOW_NUDITY_TOOLTIP: ""
 SETTING_PAUSE_ON_EVENT: ""
 SETTING_PAUSE_ON_EVENT_TOOLTIP: ""
 SETTINGS_CATEGORY_GAME_NOTIFICATIONS: ""
 SETTING_PAUSE_ON_EVENT_MESSAGE_SETTINGS: ""
 SETTING_VALUE_HOURS: ""
 SETTING_VALUE_HOUR_FULL: ""
 SETTINGS_CATEGORY_DAYNIGHT_CYCLE: ""
 SETTING_DAYNIGHT_CYCLE: ""
 SETTING_DAYNIGHT_CYCLE_TOOLTIP: ""
 SETTING_DAYNIGHT_SYSTEMTIME: ""
 SETTING_DAYNIGHT_SYSTEMTIME_TOOLTIP: ""
 SETTING_DAYNIGHT_SPEED: ""
 SETTING_DAYNIGHT_SPEED_TOOLTIP: ""
 SETTING_SUN_DURATION: ""
 SETTING_SUN_DURATION_TOOLTIP: ""
 SETTING_SUNRISE_TIME: ""
 SETTING_SUNRISE_TIME_TOOLTIP: ""
 SETTING_DAYNIGHT_SET_TIME: ""
 SETTING_DAYNIGHT_SET_TIME_TOOLTIP: ""
 SETTING_SUNRISE_SET_TIME_HOUR: ""
 SETTING_SUNRISE_SET_TIME_HOUR_TOOLTIP: ""
 SETTING_BUILDINGS_CUTOFF: ""
 SETTING_BUILDINGS_CUTOFF_TOOLTIP: ""
 SETTING_SHOW_NOTIFICATION_FEED_NEXT_TO_OUTLINER: ""
 SETTING_SHOW_NOTIFICATION_FEED_NEXT_TO_OUTLINER_TOOLTIP: ""
 SETTINGS_CATEGORY_GAME_PORTRAITS: ""
 SETTING_SOUNDTRACK: ""
 SETTING_SOUNDTRACK_TOOLTIP: ""
 SETTING_MUSIC_STINGERS: ""
 SETTING_MUSIC_STINGERS_TOOLTIP: ""
 SETTING_MUSIC: ""
 SETTING_AMBIENT: ""
 SETTING_MUSIC_TOOLTIP: ""
 SETTING_AMBIENT_TOOLTIP: ""
 SETTING_MAP_TOOLTIP_DELAY: ""
 SETTING_MAP_TOOLTIP_DELAY_TOOLTIP: ""
 SETTING_MAP_MODE_DELAY: ""
 SETTING_MAP_MODE_DELAY_TOOLTIP: ""
 SETTING_MAP_MODE_FADE_IN: ""
 SETTING_MAP_MODE_FADE_IN_TOOLTIP: ""
 SETTING_MAP_MODE_FADE_OUT: ""
 SETTING_MAP_MODE_FADE_OUT_TOOLTIP: ""
 SETTING_OCCUPATION_STRIPES: ""
 SETTING_OCCUPATION_STRIPES_TOOLTIP: ""
 SETTING_PORTRAIT_RENDER_SCALE: ""
 SETTING_PORTRAIT_RENDER_SCALE_TOOLTIP: ""
 OPTION_PORTRAIT_RENDER_SCALE_NONE: ""
 OPTION_PORTRAIT_RENDER_SCALE_MEDIUM: ""
 OPTION_PORTRAIT_RENDER_SCALE_HIGH: ""
 ui_skin_theme: ""
 ui_skin_theme_desc: ""
 papermap_theme: ""
 papermap_theme_desc: ""
 table_top_theme: ""
 table_top_theme_desc: ""
 table_asset_1_theme: ""
 table_asset_1_theme_desc: ""
 table_asset_2_theme: ""
 table_asset_2_theme_desc: ""
 table_asset_3_theme: ""
 table_asset_3_theme_desc: ""
 table_asset_4_theme: ""
 table_asset_4_theme_desc: ""
 table_asset_cloth_theme: ""
 table_asset_cloth_theme_desc: ""
 building_sets_themes: ""
 color_blind_mode_test: ""
