l_polish:
 SETTING_AUTOSAVE_TO_CLOUD: ""
 SETTING_SAVE_FILE_FORMAT: ""
 SETTING_SAVE_FILE_FORMAT_TOOLTIP: ""
 OPTION_SAVE_FILE_TEXT: ""
 OPTION_SAVE_FILE_ZIP_TEXT_ALL: ""
 OPTION_SAVE_FILE_ZIP_BINARY_ALL: ""
 SETTING_TOOLTIP_MODE: ""
 SETTING_TOOLTIP_MODE_TOOLTIP: ""
 SETTING_TOOLTIP_MODE_NO_LOCK: ""
 SETTING_TOOLTIP_MODE_MOUSE_TENDENCY: ""
 SETTING_TOOLTIP_MODE_LOCK_ON_ACTION_MOUSE_ANCHOR: ""
 SETTING_TOOLTIP_MODE_LOCK_ON_TIMER_MOUSE_ANCHOR: ""
 SETTING_TOOLTIP_MODE_LOCK_ON_ACTION_WIDGET_ANCHOR: ""
 SETTING_TOOLTIP_MODE_LOCK_ON_TIMER_WIDGET_ANCHOR: ""
 SETTING_TOOLTIP_DELAY_TOOLTIP: ""
 SETTING_TOOLTIP_DELAY: ""
 SETTING_TOOLTIP_UNLOCK_TIME: ""
 SETTING_TOOLTIP_UNLOCK_TIME_TOOLTIP: ""
 SETTING_TOOLTIP_LOCK_TIME: ""
 SETTING_TOOLTIP_LOCK_TIME_TOOLTIP: ""
 SETTING_TOOLTIP_OPEN_TIME_WHEN_ANOTHER_LOCKED: ""
 SETTING_TOOLTIP_OPEN_TIME_WHEN_ANOTHER_LOCKED_TOOLTIP: ""
 SETTINGS_CATEGORY_ADVANCED_GRAPHICS: ""
 SETTINGS_CATEGORY_AUDIO_GENERAL: ""
 SETTINGS_CATEGORY_SFX: ""
 SETTINGS_CATEGORY_MFX: ""
 SETTINGS_CATEGORY_LANGUAGE: ""
 SETTINGS_CATEGORY_SAVE_GAMES: ""
 SETTINGS_CATEGORY_TOOLTIPS: ""
 SETTINGS_CATEGORY_MAP_CONTROLS: ""
 SETTINGS_CATEGORY_MAPMODES: ""
 SETTING_SHADER_QUALITY: ""
 SETTING_SHADER_QUALITY_TOOLTIP: ""
 SETTING_SHOW_NUDITY: ""
 SETTING_SHOW_NUDITY_TOOLTIP: ""
 SETTINGS_CATEGORY_GAME_PORTRAITS: ""
 SETTING_SOUNDTRACK: ""
 SETTING_SOUNDTRACK_TOOLTIP: ""
 SETTING_MUSIC_STINGERS: ""
 SETTING_MUSIC_STINGERS_TOOLTIP: ""
 SETTING_MUSIC: ""
 SETTING_AMBIENT: ""
 SETTING_MUSIC_TOOLTIP: ""
 SETTING_AMBIENT_TOOLTIP: ""
 SETTING_MAP_TOOLTIP_DELAY: ""
 SETTING_MAP_TOOLTIP_DELAY_TOOLTIP: ""
 SETTING_MAP_MODE_DELAY: ""
 SETTING_MAP_MODE_DELAY_TOOLTIP: ""
 SETTING_MAP_MODE_FADE_IN: ""
 SETTING_MAP_MODE_FADE_IN_TOOLTIP: ""
 SETTING_MAP_MODE_FADE_OUT: ""
 SETTING_MAP_MODE_FADE_OUT_TOOLTIP: ""
 color_blind_mode_test: ""
