l_polish:
 
 SETTING_VALUE_NONE:1 "$VALUE$"
 SETTING_VALUE_TOTAL_PERCENTAGE:0 "$VALUE|%/0$"
 SETTING_VALUE_PERCENTAGE:0 "$VALUE|%0$"
 SETTING_VALUE_SECONDS:1 "$VALUE$ s"
 SETTING_VALUE_MINUTES:0 "$VALUE$ min"
 
 SETTING_RENDERER:0 "Mechanizm renderujący"
 SETTING_VSYNC:0 "Synchronizacja pionowa"
 SETTING_VSYNC_TOOLTIP:3 "#T $SETTING_VSYNC$\n#!Włączenie synchronizacji pionowej powoduje wyrównanie liczby klatek na sekundę w przypadku gry i monitora, co redukuje efekt rozchodzenia się obrazu.\n\nWyłączenie tej funkcji może poprawić wydajność."
 SETTING_PORTRAIT_MULTI_SAMPLING:0 "Wielokrotne próbkowanie portretów"
 SETTING_PORTRAIT_MULTI_SAMPLING_TOOLTIP:0 "#T $SETTING_PORTRAIT_MULTI_SAMPLING$\n#!Włączenie funkcji wielokrotnego próbkowania w przypadku techniki Alpha-To-Coverage (zamiana mieszania alfa na maskę kryjącą) powoduje wygładzenie włosów postaci.\n\nNiższe ustawienia zwiększają wydajność."
 SETTING_MULTI_SAMPLING:0 "Wygładzanie krawędzi (MSAA)"
 SETTING_MULTI_SAMPLING_TOOLTIP:2 "#T $SETTING_MULTI_SAMPLING$\n#!Włączenie funkcji wielopróbkowego wygładzania krawędzi (MSAA) sprawi, że krawędzie obrazów będą gładsze.\n\nNiższe ustawienia mogą zwiększyć wydajność."
 SETTING_ANTI_ALIASING:0 "Wygładzanie krawędzi"
 SETTING_ANTI_ALIASING_TOOLTIP:0 "#T $SETTING_ANTI_ALIASING$\n#!Włączenie funkcji wygładzania krawędzi sprawi, że krawędzie obrazów będą gładsze.\n\nZalecane jest wybranie opcji FXAA."
 OPTION_ANTI_ALIASING_DISABLED:0 "Wył."
 OPTION_ANTI_ALIASING_FXAA:0 "FXAA"
 SETTING_ANISOTROPIC_FILTERING:0 "Filtrowanie tekstur"
 SETTING_ANISOTROPIC_FILTERING_TOOLTIP:2 "#T $SETTING_ANISOTROPIC_FILTERING$\n#!Włączenie funkcji filtrowania anizotropowego poprawi wygląd tekstur powierzchni.\n\nNiższe ustawienia mogą zwiększyć wydajność."
 SETTING_FULLSCREEN_RESOLUTION:0 "Rozdzielczość"
 SETTING_FULLSCREEN_RESOLUTION_TOOLTIP:3 "#T $SETTING_FULLSCREEN_RESOLUTION$\n#!Opcja ta wpływa na jakość obrazu w grze.\n\nNiższa rozdzielczość może zwiększyć wydajność.\n\n#X Wybranie rozdzielczości o nieobsługiwanych wymiarach obrazu może spowodować wyświetlanie się interfejsów poza ekranem.#!"
 SETTING_WINDOWED_RESOLUTION:0 "Rozdzielczość w trybie okna"
 SETTING_WINDOWED_RESOLUTION_TOOLTIP:2 "#T $SETTING_WINDOWED_RESOLUTION$\n#!Funkcja ta umożliwia określenie rozdzielczości gry w trybie okna.\n\nWymagany format to #b LICZBA#!×#b LICZBA#!.\n\n#X Wybranie rozdzielczości o nieobsługiwanych wymiarach obrazu może spowodować wyświetlanie się interfejsów poza ekranem.#!"
 SETTING_RENDER_SCALE:0 "Skala renderowania"
 SETTING_RENDER_SCALE_TOOLTIP:0 "#T $SETTING_RENDER_SCALE$#!\nSkala rozdzielczości renderowania w grze związana z rozdzielczością główną. Nie dotyczy interfejsu użytkownika.\n\nNiższe ustawienia mogą zwiększyć wydajność, ale spowodują zmniejszenie ogólnej wierności obrazu. Przekroczenie wartości 100% może z kolei zwiększyć wierność obrazu, ale prawdopodobnie spowoduje spadek wydajności."
 SETTING_RENDER_SCALE_FORMAT:0 "$VALUE|%0$"
 SETTING_DISPLAY:0 "Monitor"
 SETTING_DISPLAY_TOOLTIP:2 "#T $SETTING_DISPLAY$\n#!Jeżeli do twojego komputera podłączony jest więcej niż jeden monitor, wybierz ten, na którym ma być wyświetlana gra."
 SETTING_GRAPHICS_DEVICE:0 "Karta graficzna"
 SETTING_GRAPHICS_DEVICE_TOOLTIP:2 "#T $SETTING_GRAPHICS_DEVICE$\n#!Wybierz kartę graficzną, z której ma korzystać gra. \n\nKorzystanie ze zintegrowanej karty graficznej lub oprogramowania renderującego może zmniejszyć wydajność."
 SETTING_SHADOW_MAP_RESOLUTION:0 "Jakość cieni"
 SETTING_SHADOW_MAP_RESOLUTION_TOOLTIP:2 "#T $SETTING_SHADOW_MAP_RESOLUTION$\n#!Funkcja ta pozwala określić rozdzielczość renderowania w przypadku mapowania cieni, jeśli cienie są włączone.\n\nNiższe ustawienia mogą zwiększyć wydajność."
 SETTING_DISPLAY_MODE:0 "Tryb wyświetlania"
 SETTING_DISPLAY_MODE_TOOLTIP:2 "#T $SETTING_DISPLAY_MODE$\n#!Funkcja ta pozwala określić sposób wyświetlania gry na ekranie."
 SETTING_BLOOM:0 "Rozmycie"
 SETTING_MESH_LOD_BIAS:0 "Jakość szczegółów siatki"
 SETTING_MESH_LOD_FADE:0 "Zanikanie szczegółów siatki"
 SETTING_TERRAIN_SMOOTHING:1 "Wygładzanie terenu"
 OPTION_FULLSCREEN:0 "Pełny ekran"
 OPTION_FULLSCREEN_TOOLTIP:0 "#T $OPTION_FULLSCREEN$\n#!Wybranie tego trybu powoduje wyświetlenie gry na pełnym ekranie. Ostrość obrazu zależy od wybranej rozdzielczości."
 OPTION_WINDOWED:0 "Okno"
 OPTION_WINDOWED_TOOLTIP:0 "#T $OPTION_WINDOWED$\n#!Wybranie tego trybu powoduje wyświetlenie gry w oknie. Rozmiar okna zależy od wybranej rozdzielczości."
 OPTION_DISABLED:1 "Wył."
 OPTION_OFF:0 "Wył."
 OPTION_LOW:0 "Niska"
 OPTION_MEDIUM:0 "Średnia"
 OPTION_HIGH:0 "Wysoka"
 OPTION_ULTRA:1 "Ultra"
 OPTION_CUSTOM:0 "Niestandardowa"
 OPTION_DEFAULT:1 "Domyślnie"
 SETTINGS_CATEGORY_UI:0 "Interfejs"
 SETTINGS_CATEGORY_GAME:0 "Gra"
 SETTING_TEXTURE_QUALITY:1 "Jakość tekstur"
 SETTING_TEXTURE_QUALITY_TOOLTIP:1 "#T $SETTING_TEXTURE_QUALITY$#!\nOpcja ta wpływa na rozdzielczość wczytywanych tekstur.\n\nNiższe ustawienia mogą zwiększyć wydajność."
 SETTING_QUALITY:0 "Ustawienie wstępne jakości"
 SETTING_SFX:0 "Efekty specjalne"
 SETTING_UI:0 "Interfejs"
 SETTING_QUALITY_TOOLTIP:3 "#T $SETTING_QUALITY$\n#!Wybierz jedno z poniższych ustawień wstępnych dotyczących zaawansowanych opcji grafiki.\n\nNiskie ustawienie wstępne zwiększy wydajność."
 SETTING_BLOOM_TOOLTIP:3 "#T $SETTING_BLOOM$\n#!Włączenie tej funkcji powoduje zastosowanie efektu rozmycia, który sprawia, że bardzo jasne światła wpływają na inne części obrazu.\n\nWyłączenie jej może zwiększyć wydajność."
 SETTING_DOF_TOOLTIP:0 "#T $SETTING_DOF$\n#!Funkcja głębi ostrości imituje działanie obiektywu, powodując rozmycie obrazu poza punktem ostrości.\n\nWyłączenie jej może zwiększyć wydajność."
 SETTING_MAP_SSAO_TOOLTIP:0 "#T $SETTING_MAP_SSAO$\n#!Ustawienie to umożliwia włączenie lub wyłączenie funkcji okluzji otoczenia w przestrzeni ekranu w przypadku mapy.\n\nWyłączenie jej może zwiększyć wydajność."
 SETTING_REFRACTION_TOOLTIP:0 "Ustawienie to umożliwia włączenie lub wyłączenie odbić na powierzchni wody."
 SETTING_REFRACTION_QUALITY_TOOLTIP:3 "#T $SETTING_REFRACTION_QUALITY$#!\nUstawienia te wpływają na jakość odbić na powierzchni wody, jeśli odbicia są włączone.\n\nNiższe ustawienia mogą zwiększyć wydajność."
 SETTING_MAPOBJECT_QUALITY_TOOLTIP:1 "#T $SETTING_MAPOBJECT_QUALITY$#!\nUstawienia te pozwalają określić najwyższy poziom jakości obiektów na mapie, takich jak budynki.\n\nNiższe ustawienia mogą zwiększyć wydajność."
 SETTING_MESH_LOD_BIAS_TOOLTIP:1 "#T $SETTING_MESH_LOD_BIAS$#!\nUstawienia te pozwalają określić jakość szczegółów obiektów widocznych na mapie, takich jak modele jednostek.\n\nNiższe ustawienia mogą zwiększyć wydajność."
 SETTING_MESH_LOD_FADE_TOOLTIP:3 "#T $SETTING_MESH_LOD_FADE$\n#!Włączenie tej opcji umożliwia płynną zmianę poziomów szczegółowości modeli trójwymiarowych podczas przybliżania i oddalania widoku.\n\nWyłączenie tej opcji może zwiększyć wydajność."
 SETTING_PROVINCE_NAMES_TOOLTIP:0 "Ustawienie to pozwala określić sposób wyświetlania nazw miast i prowincji na mapie."
 SETTING_FILL_IN_IMPASSABLE_TERRAIN_TOOLTIP:0 "Ustawienie to pozwala określić, czy granice państwa na mapie mają uwzględniać tereny nie do przebycia."
 SETTING_LANGUAGE_TOOLTIP:3 "#T $SETTING_LANGUAGE$#!\nUstawienie to umożliwia wybór języka interfejsu użytkownika."
 SETTING_ACCOUNT_EMAIL_TOOLTIP:0 "Twój adres e-mail konta Paradox"
 SETTING_FRAMERATE_CAP:1 "Limit klatek na sekundę"
 SETTING_FRAMERATE_CAP_TOOLTIP:1 "#T $SETTING_FRAMERATE_CAP$#!\nUstawienia te pozwalają określić maksymalną liczbę klatek na sekundę renderowanych przez grę.\n\nNiższe ustawienia mogą zmniejszyć zużycie energii."
 OPTION_CAP_30:0 "30"
 OPTION_CAP_60:0 "60"
 OPTION_CAP_90:0 "90"
 OPTION_CAP_120:0 "120"
 OPTION_CAP_144:0 "144"
 OPTION_CAP_165:0 "165"
 SETTING_TEXTURE_STREAMING:0 "Przesyłanie tekstur"
 SETTING_TEXTURE_STREAMING_CACHE:0 "Przesyłanie tekstur – ilość miejsca w pamięci podręcznej"
 SETTING_VALUE_MB:0 "$VALUE$ MB"
 
 SETTING_ANIMATION_SPEED:0 "Szybkość animacji"
 SETTING_GUI_SCALING:0 "Skalowanie graficznego interfejsu użytkownika"
 SETTING_GUI_SCALING_TOOLTIP:3 "#T $SETTING_GUI_SCALING$\n#!Funkcja ta wpływa na skalę całego interfejsu użytkownika. Przydaje się przy wyższych rozdzielczościach ekranu.\n\n#X Ustawienie zbyt wysokiej wartości sprawi, że interfejsy nie będą mieścić się na ekranie.#!"
 
 SETTING_SCREEN_EDGE_SCROLL_MODE:0 "Przesuwanie ekranu myszą"
 SETTING_SCREEN_EDGE_SCROLL_MODE_FREE:0 "Swobodne"
 SETTING_SCREEN_EDGE_SCROLL_MODE_8_DIRECTIONS:0 "8-kierunkowe"
 SETTING_SCREEN_EDGE_SCROLL_DISABLED:0 "Wył."
 SETTING_SCREEN_EDGE_SCROLL_MODE_TOOLTIP:0 "#T $SETTING_SCREEN_EDGE_SCROLL_MODE$#!\nFunkcja ta pozwala określić zachowanie kamery podczas przesuwania ekranu myszą."
 SETTING_SCROLL_SPEED:1 "Szybkość przesuwania"
 SETTING_SCROLL_SPEED_TOOLTIP:0 "#T $SETTING_SCROLL_SPEED$#!\nFunkcja ta pozwala określić szybkość przesuwania mapy za pomocą klawiatury lub myszy."
 SETTING_CAMERA_ROTATION_SPEED:1 "Szybkość obrotu kamery"
 SETTING_CAMERA_ROTATION_SPEED_TOOLTIP:0 "#T $SETTING_CAMERA_ROTATION_SPEED$#!\nFunkcja ta pozwala określić szybkość obrotu kamery."
 SETTING_ZOOM_SPEED:1 "Szybkość przybliżania"
 SETTING_ZOOM_SPEED_TOOLTIP:0 "#T $SETTING_ZOOM_SPEED$#!\nFunkcja ta pozwala określić szybkość przybliżania."
 SETTING_MOUSE_CURSOR_ZOOM_MODE:0 "Zachowanie podczas przybliżania"
 SETTING_MOUSE_CURSOR_ZOOM_MODE_RELATIVE_CURSOR:0 "Kursor względny"
 SETTING_MOUSE_CURSOR_ZOOM_MODE_ZOOM_IN_TO_CURSOR:0 "Przybliżenie na kursor"
 SETTING_MOUSE_CURSOR_ZOOM_MODE_IGNORE_CURSOR:0 "Ignorowanie kursora"
 SETTING_MOUSE_CURSOR_ZOOM_MODE_TOOLTIP:0 "#T $SETTING_MOUSE_CURSOR_ZOOM_MODE$#!\nFunkcja ta pozwala określić sposób zachowania kamery względem kursora podczas przybliżania/oddalania."
 SETTING_INPUT_DEVICE:0 "Urządzenie wejściowe"
 SETTING_EDITOR:0 "Edytor"
 SETTING_EDITOR_POSTFIX:0 "Edytor – postfiks"
 SETTING_EDITOR_OPEN_FILE_FORMAT:0 "Komenda otwarcia edytora"
 SETTING_LOG_VIEWER_OPEN_FILE_FORMAT:0 "Komenda wyświetlenia rejestru"
 SETTING_CODE_EDITOR_OPEN_FILE_FORMAT:0 "Komenda otwarcia edytora kodu"
 SETTING_GRACEFUL_EXIT:0 "Wyjście z klasą"
 SETTING_LANGUAGE:0 "Język"
 MOUSE_AND_KEYBOARD:0 "Mysz i klawiatura"
 GAMEPAD:0 "Kontroler"
 SETTING_MULTISAMPLING_DISABLED:0 "Wył."
 SETTING_PORTRAIT_MULTISAMPLING_DISABLED:0 "Wył."
 SETTING_ANISOTROPIC_FILTERING_DISABLED:0 "Wył."
 
 SETTING_CAMERA_TILT:0 "Przechylenie kamery"
 SETTING_CAMERA_STRATEGY:0 "Rodzaj kamery"
 SETTING_CENTERED_ZOOM_IN:0 "Wyśrodkowane przybliżenie"
 SETTING_CAMERA_SPEED:0 "Szybkość kamery"
 CAMERA_TABLETOP:0 "Rzut z góry"
 CAMERA_FPS:0 "Widok pierwszoosobowy"
 CAMERA_WASD:0 "Styl WASD"
 
 SETTING_Music:0 "Muzyka"
 SETTING_Ambient:0 "Dźwięki otoczenia"
 SETTING_Effects:0 "Efekty"
 SETTING_Master:0 "Głośność ogólna"
 SETTING_Master_TOOLTIP:0 "#T Głośność ogólna\n#!Ustawienie to wpływa na głośność wszystkich dźwięków w grze."
 SETTING_Music_TOOLTIP:0 "#T Głośność muzyki\n#!Ustawienie to wpływa na głośność muzyki."
 SETTING_Ambient_TOOLTIP:0 "#T Głośność dźwięków otoczenia\n#!Ustawienie to wpływa na głośność dźwięków otoczenia."
 SETTING_SFX_TOOLTIP:0 "#T Głośność efektów specjalnych\n#!Ustawienie to wpływa na głośność efektów dźwiękowych takich jak odgłosy walki."
 SETTING_UI_TOOLTIP:0 "#T Głośność interfejsu\n#!Ustawienie to wpływa na głośność interfejsu użytkownika."
 SETTING_AUDIO_DEBUG_LOG_LEVEL:0 "Poziom rejestru debugowania"
 SETTING_AUDIO_DEVICE_PROFILE:0 "Profil dźwiękowy"
 SETTING_AUDIO_DEVICE_PROFILE_TOOLTIP:0 "#T $SETTING_AUDIO_DEVICE_PROFILE$\n#!Wybierz profil dźwiękowy, który najlepiej odpowiada twojej konfiguracji."
 SETTING_AUDIO_OPTION_SPEAKERS:0 "Głośniki"
 SETTING_AUDIO_OPTION_SPEAKERS_TOOLTIP:0 "#T $SETTING_AUDIO_OPTION_SPEAKERS$\n#!Miks domyślny ($SETTING_AUDIO_OPTION_SPEAKERS$)."
 SETTING_AUDIO_OPTION_HEADPHONES:0 "Słuchawki"
 SETTING_AUDIO_OPTION_HEADPHONES_TOOLTIP:0 "#T $SETTING_AUDIO_OPTION_HEADPHONES$\n#!Miks dostosowany do urządzenia ($SETTING_AUDIO_OPTION_HEADPHONES$)."
 SETTING_AUDIO_OPTION_TV:0 "Telewizor"
 SETTING_AUDIO_OPTION_TV_TOOLTIP:0 "#T $SETTING_AUDIO_OPTION_TV$\n#!Miks dostosowany do urządzenia ($SETTING_AUDIO_OPTION_TV$ i głośniki monitora)."
 SETTING_AUDIO_OPTION_NIGHTMODE:0 "Tryb nocny"
 SETTING_AUDIO_OPTION_NIGHTMODE_TOOLTIP:0 "#T $SETTING_AUDIO_OPTION_NIGHTMODE$\n#!Wybranie tego ustawienia powoduje wyciszenie dźwięków obejmujące przytłumienie wysokich tonów i ograniczenie zakresu dynamicznego, co ułatwia rozgrywkę w nocy."
 SETTING_MUSIC_DENSITY:0 "Częstotliwość muzyki"
 SETTING_MUSIC_DENSITY_TOOLTIP:0 "Ta opcja umożliwia kontrolę balansu między kompletnymi utworami, ciszą a nastrojowymi segmentami muzycznymi. \n\nDuża intensywność – jeśli wybierzesz tę opcję, odtwarzane będą głównie utwory, jeden po drugim – jak w radiu. \nŚrednia intensywność – ta opcja zapewnia idealną równowagę między utworami, ciszą i nastrojową oprawą muzyczną. \nMała intensywność – odtwarzane będą głównie relaksujące segmenty muzyczne, które zapewniają bardziej stonowane wrażenia i pozwalają uniknąć powtarzalności po kilku godzinach rozgrywki"
  
 SETTING_AUTOSAVE:0 "Interwał automatycznego zapisu"
 SETTING_AUTOSAVE_TOOLTIP:3 "#T $SETTING_AUTOSAVE$\n#!Ustawienie to pozwala określić częstotliwość automatycznego zapisu gry."
 SETTING_AUTOSAVE_TO_CLOUD_TOOLTIP:0 "Ustawienie to pozwala określić, czy automatyczne zapisy mają być przechowywane w chmurze."
 SETTING_CAMERA_FACE_NORTH_TOOLTIP:0 "Ustawienie to pozwala określić, czy kamera ma być zawsze skierowana na północ."
 NO_AUTOSAVE:0 "Brak automatycznego zapisu"
 
 SETTINGS_FILE_TRANSFER_SPEED:0 "Prędkość przesyłania plików"
 SETTINGS_FILE_TRANSFER_SPEED_TOOLTIP:0 "#T Prędkość przesyłania plików\n#!Ustawienie to pozwala określić maksymalną prędkość przesyłania pliku z zapisanym stanem gry w lobby w trybie wieloosobowym.\n\nNiższe ustawienia mogą zwiększyć stabilność sieci podczas dołączania do gier w trybie wieloosobowym, ale wydłużają czas wczytywania trybu wieloosobowego."
 
 SETTING_MAP_EDITOR_AUTOSAVE_INTERVAL_MINUTES:0 "Automatyczny zapis w edytorze mapy (w minutach)"
 SETTING_MAP_EDITOR_AUTOSAVE_INTERVAL_MINUTES_TOOLTIP:0 "Interwał automatycznego zapisu w edytorze mapy (w minutach)"
 SETTING_NODE_EDITOR_DRAG_PAN_MODE:0 "Tryb przesuwania ekranu podczas przeciągania w edytorze węzłów"
 
 SETTINGS_CATEGORY_ACCESSIBILITY:0 "Ułatwienia dostępu"
 SETTING_COLOR_BLIND_MODE:0 "Tryb dla osób ze ślepotą barw"
 SETTING_COLOR_BLIND_MODE_TOOLTIP:0 "#T $SETTING_COLOR_BLIND_MODE$\n#!Funkcja ta umożliwia zmianę kolorów tekstów w grze, ułatwiając ich rozróżnianie osobom z różnymi rodzajami ślepoty barw."
