l_polish:
 SETTINGS_PAGE_GRAPHICS: "Grafika"
 SETTINGS_PAGE_GAME: "Gra"
 SETTINGS_PAGE_SYSTEM: "System"
 SETTINGS_PAGE_CONTROLS: "Sterowanie"
 SETTINGS_PAGE_EDITOR: "Edytor"
 SETTINGS_PAGE_INTERFACE: "Interfejs"
 SETTINGS_PAGE_AUDIO: "Dźwięk"
 SETTINGS_CATEGORY_SCREEN: "Ekran"
 SETTINGS_CATEGORY_QUALITY: "Jakość"
 OPTION_EASY: "Niski poziom trudności"
 OPTION_NORMAL: "Normalny poziom trudności"
 OPTION_HARD: "Wysoki poziom trudności"
 OPTION_NEVER: "Nigdy"
 OPTION_MONTHLY: "Co miesiąc"
 OPTION_HALFYEAR: "Co pół roku"
 OPTION_YEARLY: "Co rok"
 OPTION_FIVE_YEAR: "Co pięć lat"
 OPTION_NO_AUTOSAVE: "Nie zapisuj automatycznie"
 SETTINGS_CATEGORY_ACCOUNT: "Konto"
 SETTINGS_CATEGORY_SYSTEM: "System"
 SETTINGS_CATEGORY_CONTROLS: "Sterowanie"
 SETTINGS_CATEGORY_CAMERA: "Kamera"
 SETTINGS_CATEGORY_AUDIO: "Dźwięk"
 SETTINGS_CATEGORY_GUI: "Graficzny interfejs użytkownika"
 SETTINGS_CATEGORY_INPUT_BINDINGS: "Ustawienia sterowania"
 DISCARD: "Odrzuć"
 APPLY: "Zastosuj"
 SAVE_AND_CLOSE: "OK"
 SETTINGS: "Ustawienia"
 REQUIRES_RESTART: "Wymagane ponowne uruchomienie"
 REQUIRE_RESTART_DESCRIPTION: "Niektóre zmiany wejdą w życie dopiero po ponownym uruchomieniu gry."
 SETTINGS_INPUT_REMAP_INPUT: "Zmień przypisanie"
 SETTINGS_INPUT_CONFIRM: "Zatwierdź"
 SETTINGS_INPUT_CANCEL: "Anuluj"
 SETTINGS_INPUT_CLEAR: "Wyczyść"
 SETTINGS_INPUT_SAVE_INPUT_PROFILE: "Zapisz profil"
 SETTINGS_INPUT_LOAD_INPUT_PROFILE: "Wczytaj profil"
 SETTINGS_INPUT_RESET_INPUT_PROFILE: "Przywróć ustawienia domyślne"
 SETTINGS_INPUT_BINDING_TEXT: "Przypisz klawisz lub przycisk do czynności „$INPUT_ACTION$”:\n\n$INPUT_NAME$"
 SETTINGS_INPUT_BINDING_WARNING_TEXT: "Ostrzeżenie: do czynności „$INPUT_ACTION$” przypisano już inny klawisz lub przycisk.\nNaciśnięcie klawisza lub przycisku „$SETTINGS_INPUT_CONFIRM$” spowoduje usunięcie pierwotnego przypisania."
 SETTINGS_INPUT_BINDING_MODIFIERS_WARNING_TEXT: "Ostrzeżenie: przypisane klawisze lub przyciski nie mogą obejmować tylko klawiszy modyfikatorów"
