l_polish:
 SETTING_VALUE_NONE: ""
 SETTING_VALUE_TOTAL_PERCENTAGE: ""
 SETTING_VALUE_PERCENTAGE: ""
 SETTING_VALUE_SECONDS: ""
 SETTING_VALUE_MINUTES: ""
 SETTING_RENDERER: ""
 SETTING_RENDERER_TOOLTIP: ""
 SETTING_VSYNC: ""
 SETTING_VSYNC_TOOLTIP: ""
 SETTING_PORTRAIT_MULTI_SAMPLING: ""
 SETTING_PORTRAIT_MULTI_SAMPLING_TOOLTIP: ""
 SETTING_MULTI_SAMPLING: ""
 SETTING_MULTI_SAMPLING_TOOLTIP: ""
 SETTING_ANTI_ALIASING: ""
 SETTING_ANTI_ALIASING_TOOLTIP: ""
 OPTION_ANTI_ALIASING_DISABLED: ""
 OPTION_ANTI_ALIASING_FXAA: ""
 SETTING_UPSCALE: ""
 SETTING_UPSCALE_TOOLTIP: ""
 OPTION_UPSCALE_FSR2: ""
 OPTION_UPSCALE_DLSS: ""
 OPTION_UPSCALE_XESS: ""
 SETTING_UPSCALE_QUALITY: ""
 SETTING_UPSCALE_QUALITY_TOOLTIP: ""
 OPTION_UPSCALE_QUALITY_ULTRA_QUALITY: ""
 OPTION_UPSCALE_QUALITY_QUALITY: ""
 OPTION_UPSCALE_QUALITY_BALANCED: ""
 OPTION_UPSCALE_QUALITY_PERFORMANCE: ""
 OPTION_UPSCALE_QUALITY_ULTRA_PERFORMANCE: ""
 SETTING_ANISOTROPIC_FILTERING: ""
 SETTING_ANISOTROPIC_FILTERING_TOOLTIP: ""
 SETTING_FULLSCREEN_RESOLUTION: ""
 SETTING_FULLSCREEN_RESOLUTION_TOOLTIP: ""
 SETTING_WINDOWED_RESOLUTION: ""
 SETTING_WINDOWED_RESOLUTION_TOOLTIP: ""
 SETTING_RENDER_SCALE: ""
 SETTING_RENDER_SCALE_TOOLTIP: ""
 SETTING_RENDER_SCALE_FORMAT: ""
 SETTING_DISPLAY: ""
 SETTING_DISPLAY_TOOLTIP: ""
 SETTING_GRAPHICS_DEVICE: ""
 SETTING_GRAPHICS_DEVICE_TOOLTIP: ""
 SETTING_SHADOW_MAP_RESOLUTION: ""
 SETTING_SHADOW_MAP_RESOLUTION_TOOLTIP: ""
 SETTING_DISPLAY_MODE: ""
 SETTING_DISPLAY_MODE_TOOLTIP: ""
 SETTING_BLOOM: ""
 SETTING_MESH_LOD_BIAS: ""
 SETTING_MESH_LOD_FADE: ""
 SETTING_TERRAIN_SMOOTHING: ""
 OPTION_FULLSCREEN: ""
 OPTION_FULLSCREEN_TOOLTIP: ""
 OPTION_WINDOWED: ""
 OPTION_WINDOWED_TOOLTIP: ""
 OPTION_DISABLED: ""
 OPTION_OFF: ""
 OPTION_LOW: ""
 OPTION_MEDIUM: ""
 OPTION_HIGH: ""
 OPTION_ULTRA: ""
 OPTION_CUSTOM: ""
 OPTION_DEFAULT: ""
 SETTINGS_CATEGORY_UI: ""
 SETTINGS_CATEGORY_GAME: ""
 SETTING_TEXTURE_QUALITY: ""
 SETTING_TEXTURE_QUALITY_TOOLTIP: ""
 SETTING_QUALITY: ""
 SETTING_SFX: ""
 SETTING_UI: ""
 SETTING_QUALITY_TOOLTIP: ""
 SETTING_BLOOM_TOOLTIP: ""
 SETTING_DOF_TOOLTIP: ""
 SETTING_LENS_FLARE_TOOLTIP: ""
 SETTING_SECONDARY_LENS_FLARE_TOOLTIP: ""
 SETTING_MAP_SSAO_TOOLTIP: ""
 SETTING_REFRACTION_TOOLTIP: ""
 SETTING_REFRACTION_QUALITY_TOOLTIP: ""
 SETTING_MAPOBJECT_QUALITY_TOOLTIP: ""
 SETTING_MESH_LOD_BIAS_TOOLTIP: ""
 SETTING_MESH_LOD_FADE_TOOLTIP: ""
 SETTING_PROVINCE_NAMES_TOOLTIP: ""
 SETTING_FILL_IN_IMPASSABLE_TERRAIN_TOOLTIP: ""
 SETTING_LANGUAGE_TOOLTIP: ""
 SETTING_ACCOUNT_EMAIL_TOOLTIP: ""
 SETTING_FRAMERATE_CAP: ""
 SETTING_FRAMERATE_CAP_TOOLTIP: ""
 OPTION_CAP_30: ""
 OPTION_CAP_60: ""
 OPTION_CAP_90: ""
 OPTION_CAP_120: ""
 OPTION_CAP_144: ""
 OPTION_CAP_165: ""
 SETTING_TEXTURE_STREAMING: ""
 SETTING_TEXTURE_STREAMING_TOOLTIP: ""
 SETTING_TEXTURE_STREAMING_CACHE: ""
 SETTING_VALUE_MB: ""
 SETTING_ANIMATION_SPEED: ""
 SETTING_GUI_SCALING: ""
 SETTING_GUI_SCALING_TOOLTIP: ""
 SETTING_SCREEN_EDGE_SCROLL_MODE: ""
 SETTING_SCREEN_EDGE_SCROLL_MODE_FREE: ""
 SETTING_SCREEN_EDGE_SCROLL_MODE_8_DIRECTIONS: ""
 SETTING_SCREEN_EDGE_SCROLL_DISABLED: ""
 SETTING_SCREEN_EDGE_SCROLL_MODE_TOOLTIP: ""
 SETTING_SCROLL_SPEED: ""
 SETTING_SCROLL_SPEED_TOOLTIP: ""
 SETTING_CAMERA_ROTATION_SPEED: ""
 SETTING_CAMERA_ROTATION_SPEED_TOOLTIP: ""
 SETTING_ZOOM_SPEED: ""
 SETTING_ZOOM_SPEED_TOOLTIP: ""
 SETTING_MOUSE_CURSOR_ZOOM_MODE: ""
 SETTING_MOUSE_CURSOR_ZOOM_MODE_RELATIVE_CURSOR: ""
 SETTING_MOUSE_CURSOR_ZOOM_MODE_ZOOM_IN_TO_CURSOR: ""
 SETTING_MOUSE_CURSOR_ZOOM_MODE_IGNORE_CURSOR: ""
 SETTING_MOUSE_CURSOR_ZOOM_MODE_TOOLTIP: ""
 SETTING_INPUT_DEVICE: ""
 SETTING_EDITOR: ""
 SETTING_EDITOR_POSTFIX: ""
 SETTING_EDITOR_OPEN_FILE_FORMAT: ""
 SETTING_LOG_VIEWER_OPEN_FILE_FORMAT: ""
 SETTING_CODE_EDITOR_OPEN_FILE_FORMAT: ""
 SETTING_GRACEFUL_EXIT: ""
 SETTING_LANGUAGE: ""
 MOUSE_AND_KEYBOARD: ""
 GAMEPAD: ""
 SETTING_MULTISAMPLING_DISABLED: ""
 SETTING_PORTRAIT_MULTISAMPLING_DISABLED: ""
 SETTING_ANISOTROPIC_FILTERING_DISABLED: ""
 SETTING_CAMERA_TILT: ""
 SETTING_CAMERA_STRATEGY: ""
 SETTING_CENTERED_ZOOM_IN: ""
 SETTING_CAMERA_SPEED: ""
 CAMERA_TABLETOP: ""
 CAMERA_FPS: ""
 CAMERA_WASD: ""
 SETTING_Music: ""
 SETTING_Ambient: ""
 SETTING_Effects: ""
 SETTING_Master: ""
 SETTING_VO: ""
 SETTING_VO_TOOLTIP: ""
 SETTING_Master_TOOLTIP: ""
 SETTING_Music_TOOLTIP: ""
 SETTING_Ambient_TOOLTIP: ""
 SETTING_SFX_TOOLTIP: ""
 SETTING_UI_TOOLTIP: ""
 SETTING_AUDIO_DEBUG_LOG_LEVEL: ""
 SETTING_AUDIO_DEVICE_PROFILE: ""
 SETTING_AUDIO_DEVICE_PROFILE_TOOLTIP: ""
 SETTING_AUDIO_OPTION_SPEAKERS: ""
 SETTING_AUDIO_OPTION_SPEAKERS_TOOLTIP: ""
 SETTING_AUDIO_OPTION_HEADPHONES: ""
 SETTING_AUDIO_OPTION_HEADPHONES_TOOLTIP: ""
 SETTING_AUDIO_OPTION_TV: ""
 SETTING_AUDIO_OPTION_TV_TOOLTIP: ""
 SETTING_AUDIO_OPTION_NIGHTMODE: ""
 SETTING_AUDIO_OPTION_NIGHTMODE_TOOLTIP: ""
 SETTING_MUSIC_DENSITY: ""
 SETTING_MUSIC_DENSITY_TOOLTIP: ""
 SETTING_AUTOSAVE: ""
 SETTING_AUTOSAVE_TOOLTIP: ""
 SETTING_AUTOSAVE_TO_CLOUD_TOOLTIP: ""
 SETTING_CAMERA_FACE_NORTH_TOOLTIP: ""
 NO_AUTOSAVE: ""
 SETTINGS_FILE_TRANSFER_SPEED: ""
 SETTINGS_FILE_TRANSFER_SPEED_TOOLTIP: ""
 SETTING_MAP_EDITOR_AUTOSAVE_INTERVAL_MINUTES: ""
 SETTING_MAP_EDITOR_AUTOSAVE_INTERVAL_MINUTES_TOOLTIP: ""
 SETTING_NODE_EDITOR_DRAG_PAN_MODE: ""
 SETTINGS_CATEGORY_ACCESSIBILITY: ""
 SETTING_COLOR_BLIND_MODE: ""
 SETTING_COLOR_BLIND_MODE_TOOLTIP: ""
