l_polish:
 SETTING_REFRACTION: "Refrakcja"
 SETTING_REFRACTION_QUALITY: "Jakość refrakcji"
 SETTING_MAPOBJECT_QUALITY: "Obiekty na mapie"
 SETTING_MAP_SSAO: "Mapa – SSAO"
 SETTING_DOF: "Głębia ostrości"
